// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: advances.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAdvances = `-- name: CountAdvances :one
SELECT COUNT(*) FROM worker_advances
`

func (q *Queries) CountAdvances(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdvances)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdvance = `-- name: CreateAdvance :one
INSERT INTO worker_advances
    (worker_id, amount, reason, date_given, total_installments, installment_amount, remaining_amount)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, worker_id, amount, reason, date_given, total_installments, installment_amount, remaining_amount, status, created_at
`

type CreateAdvanceParams struct {
	WorkerID          uuid.UUID      `db:"worker_id" json:"worker_id"`
	Amount            pgtype.Numeric `db:"amount" json:"amount"`
	Reason            *string        `db:"reason" json:"reason"`
	DateGiven         time.Time      `db:"date_given" json:"date_given"`
	TotalInstallments int32          `db:"total_installments" json:"total_installments"`
	InstallmentAmount pgtype.Numeric `db:"installment_amount" json:"installment_amount"`
	RemainingAmount   pgtype.Numeric `db:"remaining_amount" json:"remaining_amount"`
}

func (q *Queries) CreateAdvance(ctx context.Context, arg CreateAdvanceParams) (WorkerAdvance, error) {
	row := q.db.QueryRow(ctx, createAdvance,
		arg.WorkerID,
		arg.Amount,
		arg.Reason,
		arg.DateGiven,
		arg.TotalInstallments,
		arg.InstallmentAmount,
		arg.RemainingAmount,
	)
	var i WorkerAdvance
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.Amount,
		&i.Reason,
		&i.DateGiven,
		&i.TotalInstallments,
		&i.InstallmentAmount,
		&i.RemainingAmount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveAdvancesForWorker = `-- name: GetActiveAdvancesForWorker :many
SELECT id, worker_id, amount, reason, date_given, total_installments, installment_amount, remaining_amount, status, created_at FROM worker_advances
WHERE worker_id = $1 AND status = 'active'
ORDER BY date_given ASC
`

func (q *Queries) GetActiveAdvancesForWorker(ctx context.Context, workerID uuid.UUID) ([]WorkerAdvance, error) {
	rows, err := q.db.Query(ctx, getActiveAdvancesForWorker, workerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkerAdvance{}
	for rows.Next() {
		var i WorkerAdvance
		if err := rows.Scan(
			&i.ID,
			&i.WorkerID,
			&i.Amount,
			&i.Reason,
			&i.DateGiven,
			&i.TotalInstallments,
			&i.InstallmentAmount,
			&i.RemainingAmount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdvanceByID = `-- name: GetAdvanceByID :one
SELECT id, worker_id, amount, reason, date_given, total_installments, installment_amount, remaining_amount, status, created_at FROM worker_advances WHERE id = $1
`

func (q *Queries) GetAdvanceByID(ctx context.Context, id uuid.UUID) (WorkerAdvance, error) {
	row := q.db.QueryRow(ctx, getAdvanceByID, id)
	var i WorkerAdvance
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.Amount,
		&i.Reason,
		&i.DateGiven,
		&i.TotalInstallments,
		&i.InstallmentAmount,
		&i.RemainingAmount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAdvanceDeductionsForPayroll = `-- name: GetAdvanceDeductionsForPayroll :many
SELECT ad.id, ad.advance_id, ad.payroll_id, ad.amount_deducted, ad.deducted_at, wa.worker_id, wa.reason
FROM advance_deductions ad
JOIN worker_advances wa ON wa.id = ad.advance_id
WHERE ad.payroll_id = $1
`

type GetAdvanceDeductionsForPayrollRow struct {
	ID             uuid.UUID      `db:"id" json:"id"`
	AdvanceID      uuid.UUID      `db:"advance_id" json:"advance_id"`
	PayrollID      uuid.UUID      `db:"payroll_id" json:"payroll_id"`
	AmountDeducted pgtype.Numeric `db:"amount_deducted" json:"amount_deducted"`
	DeductedAt     time.Time      `db:"deducted_at" json:"deducted_at"`
	WorkerID       uuid.UUID      `db:"worker_id" json:"worker_id"`
	Reason         *string        `db:"reason" json:"reason"`
}

func (q *Queries) GetAdvanceDeductionsForPayroll(ctx context.Context, payrollID uuid.UUID) ([]GetAdvanceDeductionsForPayrollRow, error) {
	rows, err := q.db.Query(ctx, getAdvanceDeductionsForPayroll, payrollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdvanceDeductionsForPayrollRow{}
	for rows.Next() {
		var i GetAdvanceDeductionsForPayrollRow
		if err := rows.Scan(
			&i.ID,
			&i.AdvanceID,
			&i.PayrollID,
			&i.AmountDeducted,
			&i.DeductedAt,
			&i.WorkerID,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdvanceTotalDeductions = `-- name: GetAdvanceTotalDeductions :one
SELECT COALESCE(SUM(amount_deducted), 0)::NUMERIC as total_deducted
FROM advance_deductions
WHERE advance_id = $1
`

func (q *Queries) GetAdvanceTotalDeductions(ctx context.Context, advanceID uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getAdvanceTotalDeductions, advanceID)
	var total_deducted pgtype.Numeric
	err := row.Scan(&total_deducted)
	return total_deducted, err
}

const listActiveAdvances = `-- name: ListActiveAdvances :many
SELECT wa.id, wa.worker_id, wa.amount, wa.reason, wa.date_given, wa.total_installments, wa.installment_amount, wa.remaining_amount, wa.status, wa.created_at, w.name as worker_name
FROM worker_advances wa
JOIN workers w ON w.id = wa.worker_id
WHERE wa.status = 'active'
ORDER BY wa.date_given DESC
`

type ListActiveAdvancesRow struct {
	ID                uuid.UUID      `db:"id" json:"id"`
	WorkerID          uuid.UUID      `db:"worker_id" json:"worker_id"`
	Amount            pgtype.Numeric `db:"amount" json:"amount"`
	Reason            *string        `db:"reason" json:"reason"`
	DateGiven         time.Time      `db:"date_given" json:"date_given"`
	TotalInstallments int32          `db:"total_installments" json:"total_installments"`
	InstallmentAmount pgtype.Numeric `db:"installment_amount" json:"installment_amount"`
	RemainingAmount   pgtype.Numeric `db:"remaining_amount" json:"remaining_amount"`
	Status            string         `db:"status" json:"status"`
	CreatedAt         time.Time      `db:"created_at" json:"created_at"`
	WorkerName        string         `db:"worker_name" json:"worker_name"`
}

func (q *Queries) ListActiveAdvances(ctx context.Context) ([]ListActiveAdvancesRow, error) {
	rows, err := q.db.Query(ctx, listActiveAdvances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAdvancesRow{}
	for rows.Next() {
		var i ListActiveAdvancesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkerID,
			&i.Amount,
			&i.Reason,
			&i.DateGiven,
			&i.TotalInstallments,
			&i.InstallmentAmount,
			&i.RemainingAmount,
			&i.Status,
			&i.CreatedAt,
			&i.WorkerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdvances = `-- name: ListAdvances :many
SELECT wa.id, wa.worker_id, wa.amount, wa.reason, wa.date_given, wa.total_installments, wa.installment_amount, wa.remaining_amount, wa.status, wa.created_at, w.name as worker_name
FROM worker_advances wa
JOIN workers w ON w.id = wa.worker_id
ORDER BY wa.date_given DESC
LIMIT $1 OFFSET $2
`

type ListAdvancesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListAdvancesRow struct {
	ID                uuid.UUID      `db:"id" json:"id"`
	WorkerID          uuid.UUID      `db:"worker_id" json:"worker_id"`
	Amount            pgtype.Numeric `db:"amount" json:"amount"`
	Reason            *string        `db:"reason" json:"reason"`
	DateGiven         time.Time      `db:"date_given" json:"date_given"`
	TotalInstallments int32          `db:"total_installments" json:"total_installments"`
	InstallmentAmount pgtype.Numeric `db:"installment_amount" json:"installment_amount"`
	RemainingAmount   pgtype.Numeric `db:"remaining_amount" json:"remaining_amount"`
	Status            string         `db:"status" json:"status"`
	CreatedAt         time.Time      `db:"created_at" json:"created_at"`
	WorkerName        string         `db:"worker_name" json:"worker_name"`
}

func (q *Queries) ListAdvances(ctx context.Context, arg ListAdvancesParams) ([]ListAdvancesRow, error) {
	rows, err := q.db.Query(ctx, listAdvances, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdvancesRow{}
	for rows.Next() {
		var i ListAdvancesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkerID,
			&i.Amount,
			&i.Reason,
			&i.DateGiven,
			&i.TotalInstallments,
			&i.InstallmentAmount,
			&i.RemainingAmount,
			&i.Status,
			&i.CreatedAt,
			&i.WorkerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkerAdvances = `-- name: ListWorkerAdvances :many
SELECT wa.id, wa.worker_id, wa.amount, wa.reason, wa.date_given, wa.total_installments, wa.installment_amount, wa.remaining_amount, wa.status, wa.created_at, w.name as worker_name
FROM worker_advances wa
JOIN workers w ON w.id = wa.worker_id
WHERE wa.worker_id = $1
ORDER BY wa.date_given DESC
`

type ListWorkerAdvancesRow struct {
	ID                uuid.UUID      `db:"id" json:"id"`
	WorkerID          uuid.UUID      `db:"worker_id" json:"worker_id"`
	Amount            pgtype.Numeric `db:"amount" json:"amount"`
	Reason            *string        `db:"reason" json:"reason"`
	DateGiven         time.Time      `db:"date_given" json:"date_given"`
	TotalInstallments int32          `db:"total_installments" json:"total_installments"`
	InstallmentAmount pgtype.Numeric `db:"installment_amount" json:"installment_amount"`
	RemainingAmount   pgtype.Numeric `db:"remaining_amount" json:"remaining_amount"`
	Status            string         `db:"status" json:"status"`
	CreatedAt         time.Time      `db:"created_at" json:"created_at"`
	WorkerName        string         `db:"worker_name" json:"worker_name"`
}

func (q *Queries) ListWorkerAdvances(ctx context.Context, workerID uuid.UUID) ([]ListWorkerAdvancesRow, error) {
	rows, err := q.db.Query(ctx, listWorkerAdvances, workerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkerAdvancesRow{}
	for rows.Next() {
		var i ListWorkerAdvancesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkerID,
			&i.Amount,
			&i.Reason,
			&i.DateGiven,
			&i.TotalInstallments,
			&i.InstallmentAmount,
			&i.RemainingAmount,
			&i.Status,
			&i.CreatedAt,
			&i.WorkerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAdvanceDeduction = `-- name: RecordAdvanceDeduction :one
INSERT INTO advance_deductions (advance_id, payroll_id, amount_deducted)
VALUES ($1, $2, $3)
RETURNING id, advance_id, payroll_id, amount_deducted, deducted_at
`

type RecordAdvanceDeductionParams struct {
	AdvanceID      uuid.UUID      `db:"advance_id" json:"advance_id"`
	PayrollID      uuid.UUID      `db:"payroll_id" json:"payroll_id"`
	AmountDeducted pgtype.Numeric `db:"amount_deducted" json:"amount_deducted"`
}

func (q *Queries) RecordAdvanceDeduction(ctx context.Context, arg RecordAdvanceDeductionParams) (AdvanceDeduction, error) {
	row := q.db.QueryRow(ctx, recordAdvanceDeduction, arg.AdvanceID, arg.PayrollID, arg.AmountDeducted)
	var i AdvanceDeduction
	err := row.Scan(
		&i.ID,
		&i.AdvanceID,
		&i.PayrollID,
		&i.AmountDeducted,
		&i.DeductedAt,
	)
	return i, err
}

const updateAdvanceRemaining = `-- name: UpdateAdvanceRemaining :one
UPDATE worker_advances
SET remaining_amount = $2, status = COALESCE($3, status)
WHERE id = $1
RETURNING id, worker_id, amount, reason, date_given, total_installments, installment_amount, remaining_amount, status, created_at
`

type UpdateAdvanceRemainingParams struct {
	ID              uuid.UUID      `db:"id" json:"id"`
	RemainingAmount pgtype.Numeric `db:"remaining_amount" json:"remaining_amount"`
	Status          string         `db:"status" json:"status"`
}

func (q *Queries) UpdateAdvanceRemaining(ctx context.Context, arg UpdateAdvanceRemainingParams) (WorkerAdvance, error) {
	row := q.db.QueryRow(ctx, updateAdvanceRemaining, arg.ID, arg.RemainingAmount, arg.Status)
	var i WorkerAdvance
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.Amount,
		&i.Reason,
		&i.DateGiven,
		&i.TotalInstallments,
		&i.InstallmentAmount,
		&i.RemainingAmount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateAdvanceStatus = `-- name: UpdateAdvanceStatus :one
UPDATE worker_advances
SET status = $2
WHERE id = $1
RETURNING id, worker_id, amount, reason, date_given, total_installments, installment_amount, remaining_amount, status, created_at
`

type UpdateAdvanceStatusParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	Status string    `db:"status" json:"status"`
}

func (q *Queries) UpdateAdvanceStatus(ctx context.Context, arg UpdateAdvanceStatusParams) (WorkerAdvance, error) {
	row := q.db.QueryRow(ctx, updateAdvanceStatus, arg.ID, arg.Status)
	var i WorkerAdvance
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.Amount,
		&i.Reason,
		&i.DateGiven,
		&i.TotalInstallments,
		&i.InstallmentAmount,
		&i.RemainingAmount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
