// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: audit_logs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_logs
WHERE ($1::text IS NULL OR $1 = '' OR entity_type = $1)
  AND ($2::uuid IS NULL OR entity_id = $2)
`

type CountAuditLogsParams struct {
	Column1 string    `db:"column_1" json:"column_1"`
	Column2 uuid.UUID `db:"column_2" json:"column_2"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (action, actor_id, actor_email, entity_type, entity_id, details)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, action, actor_id, actor_email, entity_type, entity_id, details, created_at
`

type CreateAuditLogParams struct {
	Action     string      `db:"action" json:"action"`
	ActorID    pgtype.UUID `db:"actor_id" json:"actor_id"`
	ActorEmail *string     `db:"actor_email" json:"actor_email"`
	EntityType string      `db:"entity_type" json:"entity_type"`
	EntityID   pgtype.UUID `db:"entity_id" json:"entity_id"`
	Details    []byte      `db:"details" json:"details"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.Action,
		arg.ActorID,
		arg.ActorEmail,
		arg.EntityType,
		arg.EntityID,
		arg.Details,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.ActorID,
		&i.ActorEmail,
		&i.EntityType,
		&i.EntityID,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, action, actor_id, actor_email, entity_type, entity_id, details, created_at
FROM audit_logs
WHERE ($1::text IS NULL OR $1 = '' OR entity_type = $1)
  AND ($2::uuid IS NULL OR entity_id = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListAuditLogsParams struct {
	Column1 string    `db:"column_1" json:"column_1"`
	Column2 uuid.UUID `db:"column_2" json:"column_2"`
	Limit   int32     `db:"limit" json:"limit"`
	Offset  int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.ActorID,
			&i.ActorEmail,
			&i.EntityType,
			&i.EntityID,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
