// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: commissions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countWorkerCommissions = `-- name: CountWorkerCommissions :one
SELECT COUNT(*) FROM worker_commissions WHERE worker_id = $1
`

func (q *Queries) CountWorkerCommissions(ctx context.Context, workerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkerCommissions, workerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkerCommission = `-- name: CreateWorkerCommission :one
INSERT INTO worker_commissions (worker_id, invoice_id, amount, paid_at)
VALUES ($1, $2, $3, NOW())
RETURNING id, worker_id, invoice_id, amount, status, paid_at, created_at
`

type CreateWorkerCommissionParams struct {
	WorkerID  uuid.UUID      `db:"worker_id" json:"worker_id"`
	InvoiceID uuid.UUID      `db:"invoice_id" json:"invoice_id"`
	Amount    pgtype.Numeric `db:"amount" json:"amount"`
}

func (q *Queries) CreateWorkerCommission(ctx context.Context, arg CreateWorkerCommissionParams) (WorkerCommission, error) {
	row := q.db.QueryRow(ctx, createWorkerCommission, arg.WorkerID, arg.InvoiceID, arg.Amount)
	var i WorkerCommission
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.InvoiceID,
		&i.Amount,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkerCommissionsByInvoice = `-- name: DeleteWorkerCommissionsByInvoice :exec
DELETE FROM worker_commissions WHERE invoice_id = $1
`

func (q *Queries) DeleteWorkerCommissionsByInvoice(ctx context.Context, invoiceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkerCommissionsByInvoice, invoiceID)
	return err
}

const getWorkerCommissionDetailsForMonth = `-- name: GetWorkerCommissionDetailsForMonth :many
SELECT
    wc.amount,
    wc.invoice_id,
    i.invoice_number,
    wc.paid_at AS invoice_date
FROM worker_commissions wc
JOIN invoices i ON i.id = wc.invoice_id
WHERE wc.worker_id = $1
  AND wc.paid_at >= $2
  AND wc.paid_at < $3
ORDER BY wc.paid_at DESC
`

type GetWorkerCommissionDetailsForMonthParams struct {
	WorkerID uuid.UUID `db:"worker_id" json:"worker_id"`
	PaidAt   time.Time `db:"paid_at" json:"paid_at"`
	PaidAt_2 time.Time `db:"paid_at_2" json:"paid_at_2"`
}

type GetWorkerCommissionDetailsForMonthRow struct {
	Amount        pgtype.Numeric `db:"amount" json:"amount"`
	InvoiceID     uuid.UUID      `db:"invoice_id" json:"invoice_id"`
	InvoiceNumber string         `db:"invoice_number" json:"invoice_number"`
	InvoiceDate   time.Time      `db:"invoice_date" json:"invoice_date"`
}

func (q *Queries) GetWorkerCommissionDetailsForMonth(ctx context.Context, arg GetWorkerCommissionDetailsForMonthParams) ([]GetWorkerCommissionDetailsForMonthRow, error) {
	rows, err := q.db.Query(ctx, getWorkerCommissionDetailsForMonth, arg.WorkerID, arg.PaidAt, arg.PaidAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWorkerCommissionDetailsForMonthRow{}
	for rows.Next() {
		var i GetWorkerCommissionDetailsForMonthRow
		if err := rows.Scan(
			&i.Amount,
			&i.InvoiceID,
			&i.InvoiceNumber,
			&i.InvoiceDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkerCommissionTotalByDateRange = `-- name: GetWorkerCommissionTotalByDateRange :one
SELECT COALESCE(SUM(amount), 0)::text
FROM worker_commissions
WHERE worker_id = $1
  AND ($2::date IS NULL OR paid_at::date >= $2)
  AND ($3::date IS NULL OR paid_at::date <= $3)
`

type GetWorkerCommissionTotalByDateRangeParams struct {
	WorkerID uuid.UUID `db:"worker_id" json:"worker_id"`
	Column2  time.Time `db:"column_2" json:"column_2"`
	Column3  time.Time `db:"column_3" json:"column_3"`
}

func (q *Queries) GetWorkerCommissionTotalByDateRange(ctx context.Context, arg GetWorkerCommissionTotalByDateRangeParams) (string, error) {
	row := q.db.QueryRow(ctx, getWorkerCommissionTotalByDateRange, arg.WorkerID, arg.Column2, arg.Column3)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const getWorkerCommissionTotalForMonth = `-- name: GetWorkerCommissionTotalForMonth :one
SELECT COALESCE(SUM(amount), 0)::text
FROM worker_commissions
WHERE worker_id = $1
  AND paid_at >= $2
  AND paid_at < $3
`

type GetWorkerCommissionTotalForMonthParams struct {
	WorkerID uuid.UUID `db:"worker_id" json:"worker_id"`
	PaidAt   time.Time `db:"paid_at" json:"paid_at"`
	PaidAt_2 time.Time `db:"paid_at_2" json:"paid_at_2"`
}

func (q *Queries) GetWorkerCommissionTotalForMonth(ctx context.Context, arg GetWorkerCommissionTotalForMonthParams) (string, error) {
	row := q.db.QueryRow(ctx, getWorkerCommissionTotalForMonth, arg.WorkerID, arg.PaidAt, arg.PaidAt_2)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const listWorkerCommissions = `-- name: ListWorkerCommissions :many
SELECT wc.id, wc.worker_id, wc.invoice_id, wc.amount, wc.status, wc.paid_at, wc.created_at, i.invoice_number, i.total as invoice_total, i.created_at as invoice_date
FROM worker_commissions wc
JOIN invoices i ON i.id = wc.invoice_id
WHERE wc.worker_id = $1
ORDER BY wc.paid_at DESC
LIMIT $2 OFFSET $3
`

type ListWorkerCommissionsParams struct {
	WorkerID uuid.UUID `db:"worker_id" json:"worker_id"`
	Limit    int32     `db:"limit" json:"limit"`
	Offset   int32     `db:"offset" json:"offset"`
}

type ListWorkerCommissionsRow struct {
	ID            uuid.UUID      `db:"id" json:"id"`
	WorkerID      uuid.UUID      `db:"worker_id" json:"worker_id"`
	InvoiceID     uuid.UUID      `db:"invoice_id" json:"invoice_id"`
	Amount        pgtype.Numeric `db:"amount" json:"amount"`
	Status        string         `db:"status" json:"status"`
	PaidAt        time.Time      `db:"paid_at" json:"paid_at"`
	CreatedAt     time.Time      `db:"created_at" json:"created_at"`
	InvoiceNumber string         `db:"invoice_number" json:"invoice_number"`
	InvoiceTotal  pgtype.Numeric `db:"invoice_total" json:"invoice_total"`
	InvoiceDate   time.Time      `db:"invoice_date" json:"invoice_date"`
}

func (q *Queries) ListWorkerCommissions(ctx context.Context, arg ListWorkerCommissionsParams) ([]ListWorkerCommissionsRow, error) {
	rows, err := q.db.Query(ctx, listWorkerCommissions, arg.WorkerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkerCommissionsRow{}
	for rows.Next() {
		var i ListWorkerCommissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkerID,
			&i.InvoiceID,
			&i.Amount,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
			&i.InvoiceNumber,
			&i.InvoiceTotal,
			&i.InvoiceDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkerCommissionsByDateRange = `-- name: ListWorkerCommissionsByDateRange :many
SELECT wc.id, wc.worker_id, wc.invoice_id, wc.amount, wc.status, wc.paid_at, wc.created_at, i.invoice_number, i.total as invoice_total, i.created_at as invoice_date
FROM worker_commissions wc
JOIN invoices i ON i.id = wc.invoice_id
WHERE wc.worker_id = $1
  AND ($2::date IS NULL OR wc.paid_at::date >= $2)
  AND ($3::date IS NULL OR wc.paid_at::date <= $3)
ORDER BY wc.paid_at DESC
LIMIT $4 OFFSET $5
`

type ListWorkerCommissionsByDateRangeParams struct {
	WorkerID uuid.UUID `db:"worker_id" json:"worker_id"`
	Column2  time.Time `db:"column_2" json:"column_2"`
	Column3  time.Time `db:"column_3" json:"column_3"`
	Limit    int32     `db:"limit" json:"limit"`
	Offset   int32     `db:"offset" json:"offset"`
}

type ListWorkerCommissionsByDateRangeRow struct {
	ID            uuid.UUID      `db:"id" json:"id"`
	WorkerID      uuid.UUID      `db:"worker_id" json:"worker_id"`
	InvoiceID     uuid.UUID      `db:"invoice_id" json:"invoice_id"`
	Amount        pgtype.Numeric `db:"amount" json:"amount"`
	Status        string         `db:"status" json:"status"`
	PaidAt        time.Time      `db:"paid_at" json:"paid_at"`
	CreatedAt     time.Time      `db:"created_at" json:"created_at"`
	InvoiceNumber string         `db:"invoice_number" json:"invoice_number"`
	InvoiceTotal  pgtype.Numeric `db:"invoice_total" json:"invoice_total"`
	InvoiceDate   time.Time      `db:"invoice_date" json:"invoice_date"`
}

func (q *Queries) ListWorkerCommissionsByDateRange(ctx context.Context, arg ListWorkerCommissionsByDateRangeParams) ([]ListWorkerCommissionsByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listWorkerCommissionsByDateRange,
		arg.WorkerID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkerCommissionsByDateRangeRow{}
	for rows.Next() {
		var i ListWorkerCommissionsByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkerID,
			&i.InvoiceID,
			&i.Amount,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
			&i.InvoiceNumber,
			&i.InvoiceTotal,
			&i.InvoiceDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
