// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: finance.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAccountTransactions = `-- name: CountAccountTransactions :one
SELECT COUNT(*) FROM account_transactions WHERE account_id = $1
`

func (q *Queries) CountAccountTransactions(ctx context.Context, accountID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAccountTransactions, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countExpenses = `-- name: CountExpenses :one
SELECT COUNT(*) FROM expenses
WHERE ($1::date IS NULL OR date >= $1)
  AND ($2::date IS NULL OR date <= $2)
`

type CountExpensesParams struct {
	Column1 time.Time `db:"column_1" json:"column_1"`
	Column2 time.Time `db:"column_2" json:"column_2"`
}

func (q *Queries) CountExpenses(ctx context.Context, arg CountExpensesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExpenses, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIncome = `-- name: CountIncome :one
SELECT COUNT(*) FROM income
WHERE ($1::date IS NULL OR date >= $1)
  AND ($2::date IS NULL OR date <= $2)
`

type CountIncomeParams struct {
	Column1 time.Time `db:"column_1" json:"column_1"`
	Column2 time.Time `db:"column_2" json:"column_2"`
}

func (q *Queries) CountIncome(ctx context.Context, arg CountIncomeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIncome, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccountTransaction = `-- name: CreateAccountTransaction :one
INSERT INTO account_transactions
    (account_id, transaction_type, amount, description, reference_type, reference_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, account_id, transaction_type, amount, description, reference_type, reference_id, created_at
`

type CreateAccountTransactionParams struct {
	AccountID       uuid.UUID      `db:"account_id" json:"account_id"`
	TransactionType string         `db:"transaction_type" json:"transaction_type"`
	Amount          pgtype.Numeric `db:"amount" json:"amount"`
	Description     string         `db:"description" json:"description"`
	ReferenceType   *string        `db:"reference_type" json:"reference_type"`
	ReferenceID     pgtype.UUID    `db:"reference_id" json:"reference_id"`
}

// Account Transaction Queries
func (q *Queries) CreateAccountTransaction(ctx context.Context, arg CreateAccountTransactionParams) (AccountTransaction, error) {
	row := q.db.QueryRow(ctx, createAccountTransaction,
		arg.AccountID,
		arg.TransactionType,
		arg.Amount,
		arg.Description,
		arg.ReferenceType,
		arg.ReferenceID,
	)
	var i AccountTransaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TransactionType,
		&i.Amount,
		&i.Description,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.CreatedAt,
	)
	return i, err
}

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (date, description, category, amount, vendor_payee, receipt_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, date, description, category, amount, vendor_payee, receipt_url, created_at
`

type CreateExpenseParams struct {
	Date        time.Time      `db:"date" json:"date"`
	Description string         `db:"description" json:"description"`
	Category    string         `db:"category" json:"category"`
	Amount      pgtype.Numeric `db:"amount" json:"amount"`
	VendorPayee *string        `db:"vendor_payee" json:"vendor_payee"`
	ReceiptUrl  *string        `db:"receipt_url" json:"receipt_url"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.Date,
		arg.Description,
		arg.Category,
		arg.Amount,
		arg.VendorPayee,
		arg.ReceiptUrl,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Description,
		&i.Category,
		&i.Amount,
		&i.VendorPayee,
		&i.ReceiptUrl,
		&i.CreatedAt,
	)
	return i, err
}

const createIncome = `-- name: CreateIncome :one
INSERT INTO income (date, description, category, amount, source, receipt_url, invoice_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, date, description, category, amount, source, receipt_url, created_at, invoice_id
`

type CreateIncomeParams struct {
	Date        time.Time      `db:"date" json:"date"`
	Description string         `db:"description" json:"description"`
	Category    string         `db:"category" json:"category"`
	Amount      pgtype.Numeric `db:"amount" json:"amount"`
	Source      *string        `db:"source" json:"source"`
	ReceiptUrl  *string        `db:"receipt_url" json:"receipt_url"`
	InvoiceID   pgtype.UUID    `db:"invoice_id" json:"invoice_id"`
}

func (q *Queries) CreateIncome(ctx context.Context, arg CreateIncomeParams) (Income, error) {
	row := q.db.QueryRow(ctx, createIncome,
		arg.Date,
		arg.Description,
		arg.Category,
		arg.Amount,
		arg.Source,
		arg.ReceiptUrl,
		arg.InvoiceID,
	)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Description,
		&i.Category,
		&i.Amount,
		&i.Source,
		&i.ReceiptUrl,
		&i.CreatedAt,
		&i.InvoiceID,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses WHERE id = $1
`

func (q *Queries) DeleteExpense(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpense, id)
	return err
}

const deleteIncome = `-- name: DeleteIncome :exec
DELETE FROM income WHERE id = $1
`

func (q *Queries) DeleteIncome(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIncome, id)
	return err
}

const deleteIncomeByInvoiceID = `-- name: DeleteIncomeByInvoiceID :exec
DELETE FROM income WHERE invoice_id = $1
`

func (q *Queries) DeleteIncomeByInvoiceID(ctx context.Context, invoiceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteIncomeByInvoiceID, invoiceID)
	return err
}

const getAccountTransactionByReference = `-- name: GetAccountTransactionByReference :one
SELECT id, account_id, transaction_type, amount, description, reference_type, reference_id, created_at FROM account_transactions
WHERE reference_type = $1 AND reference_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetAccountTransactionByReferenceParams struct {
	ReferenceType *string     `db:"reference_type" json:"reference_type"`
	ReferenceID   pgtype.UUID `db:"reference_id" json:"reference_id"`
}

func (q *Queries) GetAccountTransactionByReference(ctx context.Context, arg GetAccountTransactionByReferenceParams) (AccountTransaction, error) {
	row := q.db.QueryRow(ctx, getAccountTransactionByReference, arg.ReferenceType, arg.ReferenceID)
	var i AccountTransaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TransactionType,
		&i.Amount,
		&i.Description,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.CreatedAt,
	)
	return i, err
}

const getExpense = `-- name: GetExpense :one
SELECT id, date, description, category, amount, vendor_payee, receipt_url, created_at FROM expenses WHERE id = $1
`

func (q *Queries) GetExpense(ctx context.Context, id uuid.UUID) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpense, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Description,
		&i.Category,
		&i.Amount,
		&i.VendorPayee,
		&i.ReceiptUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getExpenseTotal = `-- name: GetExpenseTotal :one
SELECT COALESCE(SUM(amount), 0)::TEXT AS total
FROM expenses
WHERE ($1::date IS NULL OR date >= $1)
  AND ($2::date IS NULL OR date <= $2)
`

type GetExpenseTotalParams struct {
	Column1 time.Time `db:"column_1" json:"column_1"`
	Column2 time.Time `db:"column_2" json:"column_2"`
}

func (q *Queries) GetExpenseTotal(ctx context.Context, arg GetExpenseTotalParams) (string, error) {
	row := q.db.QueryRow(ctx, getExpenseTotal, arg.Column1, arg.Column2)
	var total string
	err := row.Scan(&total)
	return total, err
}

const getFinanceOverview = `-- name: GetFinanceOverview :one
SELECT
    COALESCE(SUM(CASE WHEN type = 'income'  THEN amount END), 0)::TEXT AS total_income,
    COALESCE(SUM(CASE WHEN type = 'expense' THEN amount END), 0)::TEXT AS total_expenses
FROM (
    SELECT amount, 'income'  AS type FROM income
    WHERE ($1::date IS NULL OR date >= $1)
      AND ($2::date IS NULL OR date <= $2)
    UNION ALL
    SELECT amount, 'expense' AS type FROM expenses
    WHERE ($1::date IS NULL OR date >= $1)
      AND ($2::date IS NULL OR date <= $2)
) combined
`

type GetFinanceOverviewParams struct {
	Column1 time.Time `db:"column_1" json:"column_1"`
	Column2 time.Time `db:"column_2" json:"column_2"`
}

type GetFinanceOverviewRow struct {
	TotalIncome   string `db:"total_income" json:"total_income"`
	TotalExpenses string `db:"total_expenses" json:"total_expenses"`
}

func (q *Queries) GetFinanceOverview(ctx context.Context, arg GetFinanceOverviewParams) (GetFinanceOverviewRow, error) {
	row := q.db.QueryRow(ctx, getFinanceOverview, arg.Column1, arg.Column2)
	var i GetFinanceOverviewRow
	err := row.Scan(&i.TotalIncome, &i.TotalExpenses)
	return i, err
}

const getIncomeByInvoiceID = `-- name: GetIncomeByInvoiceID :one
SELECT id, date, description, category, amount, source, receipt_url, created_at, invoice_id FROM income WHERE invoice_id = $1
`

func (q *Queries) GetIncomeByInvoiceID(ctx context.Context, invoiceID pgtype.UUID) (Income, error) {
	row := q.db.QueryRow(ctx, getIncomeByInvoiceID, invoiceID)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Description,
		&i.Category,
		&i.Amount,
		&i.Source,
		&i.ReceiptUrl,
		&i.CreatedAt,
		&i.InvoiceID,
	)
	return i, err
}

const getIncomeTotal = `-- name: GetIncomeTotal :one
SELECT COALESCE(SUM(amount), 0)::TEXT AS total
FROM income
WHERE ($1::date IS NULL OR date >= $1)
  AND ($2::date IS NULL OR date <= $2)
`

type GetIncomeTotalParams struct {
	Column1 time.Time `db:"column_1" json:"column_1"`
	Column2 time.Time `db:"column_2" json:"column_2"`
}

func (q *Queries) GetIncomeTotal(ctx context.Context, arg GetIncomeTotalParams) (string, error) {
	row := q.db.QueryRow(ctx, getIncomeTotal, arg.Column1, arg.Column2)
	var total string
	err := row.Scan(&total)
	return total, err
}

const getMonthlyFinanceData = `-- name: GetMonthlyFinanceData :many
SELECT
    TO_CHAR(month_series, 'Mon YYYY') AS month_label,
    month_series AS month_start,
    COALESCE(inc.total, 0)::TEXT    AS total_income,
    COALESCE(exp.total, 0)::TEXT    AS total_expenses
FROM generate_series(
    COALESCE($1::date, (date_trunc('month', NOW()) - INTERVAL '5 months')::date),
    COALESCE($2::date, date_trunc('month', NOW())::date),
    '1 month'::INTERVAL
) AS month_series
LEFT JOIN (
    SELECT date_trunc('month', date) AS m, SUM(amount) AS total
    FROM income WHERE ($1::date IS NULL OR date >= $1) AND ($2::date IS NULL OR date <= $2)
    GROUP BY m
) inc ON inc.m = month_series
LEFT JOIN (
    SELECT date_trunc('month', date) AS m, SUM(amount) AS total
    FROM expenses WHERE ($1::date IS NULL OR date >= $1) AND ($2::date IS NULL OR date <= $2)
    GROUP BY m
) exp ON exp.m = month_series
ORDER BY month_series ASC
`

type GetMonthlyFinanceDataParams struct {
	Column1 time.Time `db:"column_1" json:"column_1"`
	Column2 time.Time `db:"column_2" json:"column_2"`
}

type GetMonthlyFinanceDataRow struct {
	MonthLabel    string         `db:"month_label" json:"month_label"`
	MonthStart    pgtype.Numeric `db:"month_start" json:"month_start"`
	TotalIncome   string         `db:"total_income" json:"total_income"`
	TotalExpenses string         `db:"total_expenses" json:"total_expenses"`
}

func (q *Queries) GetMonthlyFinanceData(ctx context.Context, arg GetMonthlyFinanceDataParams) ([]GetMonthlyFinanceDataRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyFinanceData, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyFinanceDataRow{}
	for rows.Next() {
		var i GetMonthlyFinanceDataRow
		if err := rows.Scan(
			&i.MonthLabel,
			&i.MonthStart,
			&i.TotalIncome,
			&i.TotalExpenses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingPayables = `-- name: GetPendingPayables :one
SELECT COALESCE(SUM(net_payable), 0)::TEXT AS total
FROM salary_payments
WHERE status = 'pending'
`

func (q *Queries) GetPendingPayables(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getPendingPayables)
	var total string
	err := row.Scan(&total)
	return total, err
}

const getSystemAccount = `-- name: GetSystemAccount :one
SELECT id, name, current_balance, created_at FROM system_accounts WHERE id = $1
`

// System Account Queries
func (q *Queries) GetSystemAccount(ctx context.Context, id uuid.UUID) (SystemAccount, error) {
	row := q.db.QueryRow(ctx, getSystemAccount, id)
	var i SystemAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CurrentBalance,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionSummary = `-- name: GetTransactionSummary :many
SELECT
    transaction_type,
    SUM(amount) as total
FROM account_transactions
WHERE account_id = $1
  AND ($2::timestamptz IS NULL OR created_at >= $2)
  AND ($3::timestamptz IS NULL OR created_at <= $3)
GROUP BY transaction_type
`

type GetTransactionSummaryParams struct {
	AccountID uuid.UUID `db:"account_id" json:"account_id"`
	Column2   time.Time `db:"column_2" json:"column_2"`
	Column3   time.Time `db:"column_3" json:"column_3"`
}

type GetTransactionSummaryRow struct {
	TransactionType string `db:"transaction_type" json:"transaction_type"`
	Total           int64  `db:"total" json:"total"`
}

func (q *Queries) GetTransactionSummary(ctx context.Context, arg GetTransactionSummaryParams) ([]GetTransactionSummaryRow, error) {
	rows, err := q.db.Query(ctx, getTransactionSummary, arg.AccountID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTransactionSummaryRow{}
	for rows.Next() {
		var i GetTransactionSummaryRow
		if err := rows.Scan(&i.TransactionType, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountTransactions = `-- name: ListAccountTransactions :many
SELECT id, account_id, transaction_type, amount, description, reference_type, reference_id, created_at FROM account_transactions
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAccountTransactionsParams struct {
	AccountID uuid.UUID `db:"account_id" json:"account_id"`
	Limit     int32     `db:"limit" json:"limit"`
	Offset    int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListAccountTransactions(ctx context.Context, arg ListAccountTransactionsParams) ([]AccountTransaction, error) {
	rows, err := q.db.Query(ctx, listAccountTransactions, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountTransaction{}
	for rows.Next() {
		var i AccountTransaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TransactionType,
			&i.Amount,
			&i.Description,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenses = `-- name: ListExpenses :many
SELECT id, date, description, category, amount, vendor_payee, receipt_url, created_at FROM expenses
WHERE ($3::date IS NULL OR date >= $3)
  AND ($4::date IS NULL OR date <= $4)
ORDER BY date DESC
LIMIT $1 OFFSET $2
`

type ListExpensesParams struct {
	Limit   int32     `db:"limit" json:"limit"`
	Offset  int32     `db:"offset" json:"offset"`
	Column3 time.Time `db:"column_3" json:"column_3"`
	Column4 time.Time `db:"column_4" json:"column_4"`
}

func (q *Queries) ListExpenses(ctx context.Context, arg ListExpensesParams) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpenses,
		arg.Limit,
		arg.Offset,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Expense{}
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Description,
			&i.Category,
			&i.Amount,
			&i.VendorPayee,
			&i.ReceiptUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncome = `-- name: ListIncome :many
SELECT id, date, description, category, amount, source, receipt_url, created_at, invoice_id FROM income
WHERE ($3::date IS NULL OR date >= $3)
  AND ($4::date IS NULL OR date <= $4)
ORDER BY date DESC
LIMIT $1 OFFSET $2
`

type ListIncomeParams struct {
	Limit   int32     `db:"limit" json:"limit"`
	Offset  int32     `db:"offset" json:"offset"`
	Column3 time.Time `db:"column_3" json:"column_3"`
	Column4 time.Time `db:"column_4" json:"column_4"`
}

func (q *Queries) ListIncome(ctx context.Context, arg ListIncomeParams) ([]Income, error) {
	rows, err := q.db.Query(ctx, listIncome,
		arg.Limit,
		arg.Offset,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Income{}
	for rows.Next() {
		var i Income
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Description,
			&i.Category,
			&i.Amount,
			&i.Source,
			&i.ReceiptUrl,
			&i.CreatedAt,
			&i.InvoiceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemAccounts = `-- name: ListSystemAccounts :many
SELECT id, name, current_balance, created_at FROM system_accounts ORDER BY name ASC
`

func (q *Queries) ListSystemAccounts(ctx context.Context) ([]SystemAccount, error) {
	rows, err := q.db.Query(ctx, listSystemAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemAccount{}
	for rows.Next() {
		var i SystemAccount
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CurrentBalance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :one
UPDATE system_accounts
SET current_balance = current_balance + $2
WHERE id = $1
RETURNING id, name, current_balance, created_at
`

type UpdateAccountBalanceParams struct {
	ID             uuid.UUID      `db:"id" json:"id"`
	CurrentBalance pgtype.Numeric `db:"current_balance" json:"current_balance"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (SystemAccount, error) {
	row := q.db.QueryRow(ctx, updateAccountBalance, arg.ID, arg.CurrentBalance)
	var i SystemAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CurrentBalance,
		&i.CreatedAt,
	)
	return i, err
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET
    date         = COALESCE($2, date),
    description  = COALESCE($3, description),
    category     = COALESCE($4, category),
    amount       = COALESCE($5, amount),
    vendor_payee = COALESCE($6, vendor_payee),
    receipt_url  = COALESCE($7, receipt_url),
    updated_at   = NOW()
WHERE id = $1
RETURNING id, date, description, category, amount, vendor_payee, receipt_url, created_at
`

type UpdateExpenseParams struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	Date        pgtype.Date    `db:"date" json:"date"`
	Description *string        `db:"description" json:"description"`
	Category    *string        `db:"category" json:"category"`
	Amount      pgtype.Numeric `db:"amount" json:"amount"`
	VendorPayee *string        `db:"vendor_payee" json:"vendor_payee"`
	ReceiptUrl  *string        `db:"receipt_url" json:"receipt_url"`
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.ID,
		arg.Date,
		arg.Description,
		arg.Category,
		arg.Amount,
		arg.VendorPayee,
		arg.ReceiptUrl,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Description,
		&i.Category,
		&i.Amount,
		&i.VendorPayee,
		&i.ReceiptUrl,
		&i.CreatedAt,
	)
	return i, err
}

const updateIncome = `-- name: UpdateIncome :one
UPDATE income
SET
    date        = COALESCE($2, date),
    description = COALESCE($3, description),
    category    = COALESCE($4, category),
    amount      = COALESCE($5, amount),
    source      = COALESCE($6, source),
    receipt_url = COALESCE($7, receipt_url),
    invoice_id  = COALESCE($8, invoice_id),
    updated_at  = NOW()
WHERE id = $1
RETURNING id, date, description, category, amount, source, receipt_url, created_at, invoice_id
`

type UpdateIncomeParams struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	Date        pgtype.Date    `db:"date" json:"date"`
	Description *string        `db:"description" json:"description"`
	Category    *string        `db:"category" json:"category"`
	Amount      pgtype.Numeric `db:"amount" json:"amount"`
	Source      *string        `db:"source" json:"source"`
	ReceiptUrl  *string        `db:"receipt_url" json:"receipt_url"`
	InvoiceID   pgtype.UUID    `db:"invoice_id" json:"invoice_id"`
}

func (q *Queries) UpdateIncome(ctx context.Context, arg UpdateIncomeParams) (Income, error) {
	row := q.db.QueryRow(ctx, updateIncome,
		arg.ID,
		arg.Date,
		arg.Description,
		arg.Category,
		arg.Amount,
		arg.Source,
		arg.ReceiptUrl,
		arg.InvoiceID,
	)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Description,
		&i.Category,
		&i.Amount,
		&i.Source,
		&i.ReceiptUrl,
		&i.CreatedAt,
		&i.InvoiceID,
	)
	return i, err
}
