// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: inventory.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInventoryItem = `-- name: CreateInventoryItem :one
INSERT INTO inventory (
    name, category, quantity, unit, condition,
    assigned_worker_id, purchase_date, cost, low_stock_threshold
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, category, quantity, unit, condition, assigned_worker_id, purchase_date, cost, low_stock_threshold, created_at, updated_at
`

type CreateInventoryItemParams struct {
	Name              string         `db:"name" json:"name"`
	Category          string         `db:"category" json:"category"`
	Quantity          int32          `db:"quantity" json:"quantity"`
	Unit              string         `db:"unit" json:"unit"`
	Condition         string         `db:"condition" json:"condition"`
	AssignedWorkerID  pgtype.UUID    `db:"assigned_worker_id" json:"assigned_worker_id"`
	PurchaseDate      pgtype.Date    `db:"purchase_date" json:"purchase_date"`
	Cost              pgtype.Numeric `db:"cost" json:"cost"`
	LowStockThreshold int32          `db:"low_stock_threshold" json:"low_stock_threshold"`
}

func (q *Queries) CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, createInventoryItem,
		arg.Name,
		arg.Category,
		arg.Quantity,
		arg.Unit,
		arg.Condition,
		arg.AssignedWorkerID,
		arg.PurchaseDate,
		arg.Cost,
		arg.LowStockThreshold,
	)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Quantity,
		&i.Unit,
		&i.Condition,
		&i.AssignedWorkerID,
		&i.PurchaseDate,
		&i.Cost,
		&i.LowStockThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInventoryItem = `-- name: DeleteInventoryItem :exec
DELETE FROM inventory WHERE id = $1
`

func (q *Queries) DeleteInventoryItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInventoryItem, id)
	return err
}

const getInventoryItemByID = `-- name: GetInventoryItemByID :one
SELECT i.id, i.name, i.category, i.quantity, i.unit, i.condition, i.assigned_worker_id, i.purchase_date, i.cost, i.low_stock_threshold, i.created_at, i.updated_at, w.name AS worker_name
FROM inventory i
LEFT JOIN workers w ON w.id = i.assigned_worker_id
WHERE i.id = $1
`

type GetInventoryItemByIDRow struct {
	ID                uuid.UUID      `db:"id" json:"id"`
	Name              string         `db:"name" json:"name"`
	Category          string         `db:"category" json:"category"`
	Quantity          int32          `db:"quantity" json:"quantity"`
	Unit              string         `db:"unit" json:"unit"`
	Condition         string         `db:"condition" json:"condition"`
	AssignedWorkerID  pgtype.UUID    `db:"assigned_worker_id" json:"assigned_worker_id"`
	PurchaseDate      pgtype.Date    `db:"purchase_date" json:"purchase_date"`
	Cost              pgtype.Numeric `db:"cost" json:"cost"`
	LowStockThreshold int32          `db:"low_stock_threshold" json:"low_stock_threshold"`
	CreatedAt         time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time      `db:"updated_at" json:"updated_at"`
	WorkerName        *string        `db:"worker_name" json:"worker_name"`
}

func (q *Queries) GetInventoryItemByID(ctx context.Context, id uuid.UUID) (GetInventoryItemByIDRow, error) {
	row := q.db.QueryRow(ctx, getInventoryItemByID, id)
	var i GetInventoryItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Quantity,
		&i.Unit,
		&i.Condition,
		&i.AssignedWorkerID,
		&i.PurchaseDate,
		&i.Cost,
		&i.LowStockThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkerName,
	)
	return i, err
}

const listInventory = `-- name: ListInventory :many
SELECT i.id, i.name, i.category, i.quantity, i.unit, i.condition, i.assigned_worker_id, i.purchase_date, i.cost, i.low_stock_threshold, i.created_at, i.updated_at, w.name AS worker_name
FROM inventory i
LEFT JOIN workers w ON w.id = i.assigned_worker_id
ORDER BY i.name ASC
`

type ListInventoryRow struct {
	ID                uuid.UUID      `db:"id" json:"id"`
	Name              string         `db:"name" json:"name"`
	Category          string         `db:"category" json:"category"`
	Quantity          int32          `db:"quantity" json:"quantity"`
	Unit              string         `db:"unit" json:"unit"`
	Condition         string         `db:"condition" json:"condition"`
	AssignedWorkerID  pgtype.UUID    `db:"assigned_worker_id" json:"assigned_worker_id"`
	PurchaseDate      pgtype.Date    `db:"purchase_date" json:"purchase_date"`
	Cost              pgtype.Numeric `db:"cost" json:"cost"`
	LowStockThreshold int32          `db:"low_stock_threshold" json:"low_stock_threshold"`
	CreatedAt         time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time      `db:"updated_at" json:"updated_at"`
	WorkerName        *string        `db:"worker_name" json:"worker_name"`
}

func (q *Queries) ListInventory(ctx context.Context) ([]ListInventoryRow, error) {
	rows, err := q.db.Query(ctx, listInventory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInventoryRow{}
	for rows.Next() {
		var i ListInventoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Quantity,
			&i.Unit,
			&i.Condition,
			&i.AssignedWorkerID,
			&i.PurchaseDate,
			&i.Cost,
			&i.LowStockThreshold,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInventoryItem = `-- name: UpdateInventoryItem :one
UPDATE inventory
SET
    name                = COALESCE($2, name),
    category            = COALESCE($3, category),
    quantity            = COALESCE($4, quantity),
    unit                = COALESCE($5, unit),
    condition           = COALESCE($6, condition),
    assigned_worker_id  = COALESCE($7, assigned_worker_id),
    purchase_date       = COALESCE($8, purchase_date),
    cost                = COALESCE($9, cost),
    low_stock_threshold = COALESCE($10, low_stock_threshold),
    updated_at          = NOW()
WHERE id = $1
RETURNING id, name, category, quantity, unit, condition, assigned_worker_id, purchase_date, cost, low_stock_threshold, created_at, updated_at
`

type UpdateInventoryItemParams struct {
	ID                uuid.UUID      `db:"id" json:"id"`
	Name              *string        `db:"name" json:"name"`
	Category          *string        `db:"category" json:"category"`
	Quantity          *int32         `db:"quantity" json:"quantity"`
	Unit              *string        `db:"unit" json:"unit"`
	Condition         *string        `db:"condition" json:"condition"`
	AssignedWorkerID  pgtype.UUID    `db:"assigned_worker_id" json:"assigned_worker_id"`
	PurchaseDate      pgtype.Date    `db:"purchase_date" json:"purchase_date"`
	Cost              pgtype.Numeric `db:"cost" json:"cost"`
	LowStockThreshold *int32         `db:"low_stock_threshold" json:"low_stock_threshold"`
}

func (q *Queries) UpdateInventoryItem(ctx context.Context, arg UpdateInventoryItemParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, updateInventoryItem,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.Quantity,
		arg.Unit,
		arg.Condition,
		arg.AssignedWorkerID,
		arg.PurchaseDate,
		arg.Cost,
		arg.LowStockThreshold,
	)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Quantity,
		&i.Unit,
		&i.Condition,
		&i.AssignedWorkerID,
		&i.PurchaseDate,
		&i.Cost,
		&i.LowStockThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
