// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: invoices.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countInvoices = `-- name: CountInvoices :one
SELECT COUNT(*) FROM invoices
WHERE ($1::text IS NULL OR $1 = '' OR status = $1)
  AND ($2::date IS NULL OR $2 = '0001-01-01' OR created_at::date >= $2)
  AND ($3::date IS NULL OR $3 = '0001-01-01' OR created_at::date <= $3)
`

type CountInvoicesParams struct {
	Column1 string    `db:"column_1" json:"column_1"`
	Column2 time.Time `db:"column_2" json:"column_2"`
	Column3 time.Time `db:"column_3" json:"column_3"`
}

func (q *Queries) CountInvoices(ctx context.Context, arg CountInvoicesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoices, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequestsWithoutInvoice = `-- name: CountRequestsWithoutInvoice :one
SELECT COUNT(*)
FROM service_requests sr
LEFT JOIN invoices inv ON inv.request_id = sr.id
WHERE inv.id IS NULL
  AND sr.status != 'invoiced'
`

func (q *Queries) CountRequestsWithoutInvoice(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestsWithoutInvoice)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
    invoice_number, request_id, client_id, client_name, client_address, client_phone,
    service_name, service_description, subtotal, total, notes, status, vendor_commission
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, invoice_number, request_id, client_id, client_name, client_address, client_phone, service_name, service_description, discount, subtotal, total, notes, status, created_at, updated_at, vendor_commission
`

type CreateInvoiceParams struct {
	InvoiceNumber      string         `db:"invoice_number" json:"invoice_number"`
	RequestID          pgtype.UUID    `db:"request_id" json:"request_id"`
	ClientID           uuid.UUID      `db:"client_id" json:"client_id"`
	ClientName         string         `db:"client_name" json:"client_name"`
	ClientAddress      *string        `db:"client_address" json:"client_address"`
	ClientPhone        *string        `db:"client_phone" json:"client_phone"`
	ServiceName        string         `db:"service_name" json:"service_name"`
	ServiceDescription *string        `db:"service_description" json:"service_description"`
	Subtotal           pgtype.Numeric `db:"subtotal" json:"subtotal"`
	Total              pgtype.Numeric `db:"total" json:"total"`
	Notes              *string        `db:"notes" json:"notes"`
	Status             string         `db:"status" json:"status"`
	VendorCommission   pgtype.Numeric `db:"vendor_commission" json:"vendor_commission"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.InvoiceNumber,
		arg.RequestID,
		arg.ClientID,
		arg.ClientName,
		arg.ClientAddress,
		arg.ClientPhone,
		arg.ServiceName,
		arg.ServiceDescription,
		arg.Subtotal,
		arg.Total,
		arg.Notes,
		arg.Status,
		arg.VendorCommission,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.RequestID,
		&i.ClientID,
		&i.ClientName,
		&i.ClientAddress,
		&i.ClientPhone,
		&i.ServiceName,
		&i.ServiceDescription,
		&i.Discount,
		&i.Subtotal,
		&i.Total,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VendorCommission,
	)
	return i, err
}

const createInvoiceCommission = `-- name: CreateInvoiceCommission :one
INSERT INTO invoice_commissions (invoice_id, worker_id, amount, created_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (invoice_id, worker_id)
DO UPDATE SET amount = EXCLUDED.amount, created_by = EXCLUDED.created_by
RETURNING id, invoice_id, worker_id, amount, created_at, created_by
`

type CreateInvoiceCommissionParams struct {
	InvoiceID uuid.UUID      `db:"invoice_id" json:"invoice_id"`
	WorkerID  uuid.UUID      `db:"worker_id" json:"worker_id"`
	Amount    pgtype.Numeric `db:"amount" json:"amount"`
	CreatedBy pgtype.UUID    `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateInvoiceCommission(ctx context.Context, arg CreateInvoiceCommissionParams) (InvoiceCommission, error) {
	row := q.db.QueryRow(ctx, createInvoiceCommission,
		arg.InvoiceID,
		arg.WorkerID,
		arg.Amount,
		arg.CreatedBy,
	)
	var i InvoiceCommission
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.WorkerID,
		&i.Amount,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const createLineItem = `-- name: CreateLineItem :one
INSERT INTO invoice_line_items (invoice_id, description, quantity, rate, amount)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, invoice_id, description, quantity, rate, amount
`

type CreateLineItemParams struct {
	InvoiceID   uuid.UUID      `db:"invoice_id" json:"invoice_id"`
	Description string         `db:"description" json:"description"`
	Quantity    pgtype.Numeric `db:"quantity" json:"quantity"`
	Rate        pgtype.Numeric `db:"rate" json:"rate"`
	Amount      pgtype.Numeric `db:"amount" json:"amount"`
}

func (q *Queries) CreateLineItem(ctx context.Context, arg CreateLineItemParams) (InvoiceLineItem, error) {
	row := q.db.QueryRow(ctx, createLineItem,
		arg.InvoiceID,
		arg.Description,
		arg.Quantity,
		arg.Rate,
		arg.Amount,
	)
	var i InvoiceLineItem
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Description,
		&i.Quantity,
		&i.Rate,
		&i.Amount,
	)
	return i, err
}

const deleteInvoice = `-- name: DeleteInvoice :exec
DELETE FROM invoices WHERE id = $1
`

func (q *Queries) DeleteInvoice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvoice, id)
	return err
}

const deleteInvoiceCommissionsByInvoice = `-- name: DeleteInvoiceCommissionsByInvoice :exec
DELETE FROM invoice_commissions WHERE invoice_id = $1
`

func (q *Queries) DeleteInvoiceCommissionsByInvoice(ctx context.Context, invoiceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvoiceCommissionsByInvoice, invoiceID)
	return err
}

const deleteLineItemsByInvoice = `-- name: DeleteLineItemsByInvoice :exec
DELETE FROM invoice_line_items WHERE invoice_id = $1
`

func (q *Queries) DeleteLineItemsByInvoice(ctx context.Context, invoiceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLineItemsByInvoice, invoiceID)
	return err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, invoice_number, request_id, client_id, client_name, client_address, client_phone, service_name, service_description, discount, subtotal, total, notes, status, created_at, updated_at, vendor_commission FROM invoices WHERE id = $1
`

func (q *Queries) GetInvoiceByID(ctx context.Context, id uuid.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.RequestID,
		&i.ClientID,
		&i.ClientName,
		&i.ClientAddress,
		&i.ClientPhone,
		&i.ServiceName,
		&i.ServiceDescription,
		&i.Discount,
		&i.Subtotal,
		&i.Total,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VendorCommission,
	)
	return i, err
}

const getNextInvoiceNumber = `-- name: GetNextInvoiceNumber :one
SELECT COALESCE(
    'INV-' || LPAD(
        (CAST(SUBSTRING(MAX(invoice_number) FROM 'INV-([0-9]+)') AS INTEGER) + 1)::TEXT,
        4, '0'
    ),
    'INV-0001'
) AS next_number
FROM invoices
`

func (q *Queries) GetNextInvoiceNumber(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, getNextInvoiceNumber)
	var next_number interface{}
	err := row.Scan(&next_number)
	return next_number, err
}

const getWorkerInvoiceCommissionTotal = `-- name: GetWorkerInvoiceCommissionTotal :one
SELECT COALESCE(SUM(ic.amount), 0)::text AS total
FROM invoice_commissions ic
JOIN invoices i ON i.id = ic.invoice_id
WHERE ic.worker_id = $1
  AND i.created_at >= $2
  AND i.created_at < $3
`

type GetWorkerInvoiceCommissionTotalParams struct {
	WorkerID    uuid.UUID `db:"worker_id" json:"worker_id"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	CreatedAt_2 time.Time `db:"created_at_2" json:"created_at_2"`
}

func (q *Queries) GetWorkerInvoiceCommissionTotal(ctx context.Context, arg GetWorkerInvoiceCommissionTotalParams) (string, error) {
	row := q.db.QueryRow(ctx, getWorkerInvoiceCommissionTotal, arg.WorkerID, arg.CreatedAt, arg.CreatedAt_2)
	var total string
	err := row.Scan(&total)
	return total, err
}

const getWorkerPaidCommissionTotalForMonth = `-- name: GetWorkerPaidCommissionTotalForMonth :one
SELECT COALESCE(SUM(wc.amount), 0)::TEXT AS total
FROM worker_commissions wc
WHERE wc.worker_id = $1
  AND wc.paid_at >= $2
  AND wc.paid_at < $3
`

type GetWorkerPaidCommissionTotalForMonthParams struct {
	WorkerID uuid.UUID `db:"worker_id" json:"worker_id"`
	PaidAt   time.Time `db:"paid_at" json:"paid_at"`
	PaidAt_2 time.Time `db:"paid_at_2" json:"paid_at_2"`
}

func (q *Queries) GetWorkerPaidCommissionTotalForMonth(ctx context.Context, arg GetWorkerPaidCommissionTotalForMonthParams) (string, error) {
	row := q.db.QueryRow(ctx, getWorkerPaidCommissionTotalForMonth, arg.WorkerID, arg.PaidAt, arg.PaidAt_2)
	var total string
	err := row.Scan(&total)
	return total, err
}

const listInvoiceCommissions = `-- name: ListInvoiceCommissions :many
SELECT ic.id, ic.invoice_id, ic.worker_id, ic.amount, ic.created_at, ic.created_by, w.name AS worker_name
FROM invoice_commissions ic
JOIN workers w ON w.id = ic.worker_id
WHERE ic.invoice_id = $1
ORDER BY w.name ASC
`

type ListInvoiceCommissionsRow struct {
	ID         uuid.UUID      `db:"id" json:"id"`
	InvoiceID  uuid.UUID      `db:"invoice_id" json:"invoice_id"`
	WorkerID   uuid.UUID      `db:"worker_id" json:"worker_id"`
	Amount     pgtype.Numeric `db:"amount" json:"amount"`
	CreatedAt  time.Time      `db:"created_at" json:"created_at"`
	CreatedBy  pgtype.UUID    `db:"created_by" json:"created_by"`
	WorkerName string         `db:"worker_name" json:"worker_name"`
}

func (q *Queries) ListInvoiceCommissions(ctx context.Context, invoiceID uuid.UUID) ([]ListInvoiceCommissionsRow, error) {
	rows, err := q.db.Query(ctx, listInvoiceCommissions, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoiceCommissionsRow{}
	for rows.Next() {
		var i ListInvoiceCommissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.WorkerID,
			&i.Amount,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.WorkerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoices = `-- name: ListInvoices :many
SELECT i.id, i.invoice_number, i.request_id, i.client_id, i.client_name, i.client_address, i.client_phone, i.service_name, i.service_description, i.discount, i.subtotal, i.total, i.notes, i.status, i.created_at, i.updated_at, i.vendor_commission, u.name AS client_user_name
FROM invoices i
JOIN users u ON u.id = i.client_id
WHERE ($1::text IS NULL OR $1 = '' OR i.status = $1)
  AND ($4::date IS NULL OR $4 = '0001-01-01' OR i.created_at::date >= $4)
  AND ($5::date IS NULL OR $5 = '0001-01-01' OR i.created_at::date <= $5)
ORDER BY i.created_at DESC
LIMIT $2 OFFSET $3
`

type ListInvoicesParams struct {
	Column1 string    `db:"column_1" json:"column_1"`
	Limit   int32     `db:"limit" json:"limit"`
	Offset  int32     `db:"offset" json:"offset"`
	Column4 time.Time `db:"column_4" json:"column_4"`
	Column5 time.Time `db:"column_5" json:"column_5"`
}

type ListInvoicesRow struct {
	ID                 uuid.UUID      `db:"id" json:"id"`
	InvoiceNumber      string         `db:"invoice_number" json:"invoice_number"`
	RequestID          pgtype.UUID    `db:"request_id" json:"request_id"`
	ClientID           uuid.UUID      `db:"client_id" json:"client_id"`
	ClientName         string         `db:"client_name" json:"client_name"`
	ClientAddress      *string        `db:"client_address" json:"client_address"`
	ClientPhone        *string        `db:"client_phone" json:"client_phone"`
	ServiceName        string         `db:"service_name" json:"service_name"`
	ServiceDescription *string        `db:"service_description" json:"service_description"`
	Discount           pgtype.Numeric `db:"discount" json:"discount"`
	Subtotal           pgtype.Numeric `db:"subtotal" json:"subtotal"`
	Total              pgtype.Numeric `db:"total" json:"total"`
	Notes              *string        `db:"notes" json:"notes"`
	Status             string         `db:"status" json:"status"`
	CreatedAt          time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt          time.Time      `db:"updated_at" json:"updated_at"`
	VendorCommission   pgtype.Numeric `db:"vendor_commission" json:"vendor_commission"`
	ClientUserName     string         `db:"client_user_name" json:"client_user_name"`
}

func (q *Queries) ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]ListInvoicesRow, error) {
	rows, err := q.db.Query(ctx, listInvoices,
		arg.Column1,
		arg.Limit,
		arg.Offset,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoicesRow{}
	for rows.Next() {
		var i ListInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.RequestID,
			&i.ClientID,
			&i.ClientName,
			&i.ClientAddress,
			&i.ClientPhone,
			&i.ServiceName,
			&i.ServiceDescription,
			&i.Discount,
			&i.Subtotal,
			&i.Total,
			&i.Notes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VendorCommission,
			&i.ClientUserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLineItemsByInvoice = `-- name: ListLineItemsByInvoice :many
SELECT id, invoice_id, description, quantity, rate, amount FROM invoice_line_items WHERE invoice_id = $1
`

func (q *Queries) ListLineItemsByInvoice(ctx context.Context, invoiceID uuid.UUID) ([]InvoiceLineItem, error) {
	rows, err := q.db.Query(ctx, listLineItemsByInvoice, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceLineItem{}
	for rows.Next() {
		var i InvoiceLineItem
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.Description,
			&i.Quantity,
			&i.Rate,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsWithoutInvoice = `-- name: ListRequestsWithoutInvoice :many
SELECT
    sr.id, sr.request_number, sr.client_id, sr.service_id, sr.description,
    sr.preferred_date, sr.preferred_time, sr.urgency, sr.full_name, sr.phone,
    sr.email, sr.address, sr.city, sr.area, sr.status, sr.assigned_worker_id,
    sr.internal_notes, sr.created_at, sr.updated_at,
    s.name AS service_name,
    COALESCE(li.service_summary, s.name) AS service_summary,
    COALESCE(wc.worker_count, 0)::bigint AS worker_count
FROM service_requests sr
JOIN services s ON s.id = sr.service_id
LEFT JOIN invoices inv ON inv.request_id = sr.id
LEFT JOIN (
    SELECT rli.request_id, STRING_AGG(s2.name, ', ' ORDER BY rli.created_at) AS service_summary
    FROM request_line_items rli
    JOIN services s2 ON s2.id = rli.service_id
    GROUP BY rli.request_id
) li ON li.request_id = sr.id
LEFT JOIN (
    SELECT request_id, COUNT(*)::bigint AS worker_count
    FROM request_workers
    GROUP BY request_id
) wc ON wc.request_id = sr.id
WHERE inv.id IS NULL
  AND sr.status != 'invoiced'
ORDER BY sr.created_at DESC
LIMIT $1 OFFSET $2
`

type ListRequestsWithoutInvoiceParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListRequestsWithoutInvoiceRow struct {
	ID               uuid.UUID   `db:"id" json:"id"`
	RequestNumber    string      `db:"request_number" json:"request_number"`
	ClientID         uuid.UUID   `db:"client_id" json:"client_id"`
	ServiceID        uuid.UUID   `db:"service_id" json:"service_id"`
	Description      string      `db:"description" json:"description"`
	PreferredDate    time.Time   `db:"preferred_date" json:"preferred_date"`
	PreferredTime    string      `db:"preferred_time" json:"preferred_time"`
	Urgency          string      `db:"urgency" json:"urgency"`
	FullName         string      `db:"full_name" json:"full_name"`
	Phone            string      `db:"phone" json:"phone"`
	Email            string      `db:"email" json:"email"`
	Address          string      `db:"address" json:"address"`
	City             string      `db:"city" json:"city"`
	Area             string      `db:"area" json:"area"`
	Status           string      `db:"status" json:"status"`
	AssignedWorkerID pgtype.UUID `db:"assigned_worker_id" json:"assigned_worker_id"`
	InternalNotes    *string     `db:"internal_notes" json:"internal_notes"`
	CreatedAt        time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time   `db:"updated_at" json:"updated_at"`
	ServiceName      string      `db:"service_name" json:"service_name"`
	ServiceSummary   []byte      `db:"service_summary" json:"service_summary"`
	WorkerCount      int64       `db:"worker_count" json:"worker_count"`
}

func (q *Queries) ListRequestsWithoutInvoice(ctx context.Context, arg ListRequestsWithoutInvoiceParams) ([]ListRequestsWithoutInvoiceRow, error) {
	rows, err := q.db.Query(ctx, listRequestsWithoutInvoice, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestsWithoutInvoiceRow{}
	for rows.Next() {
		var i ListRequestsWithoutInvoiceRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestNumber,
			&i.ClientID,
			&i.ServiceID,
			&i.Description,
			&i.PreferredDate,
			&i.PreferredTime,
			&i.Urgency,
			&i.FullName,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.City,
			&i.Area,
			&i.Status,
			&i.AssignedWorkerID,
			&i.InternalNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceName,
			&i.ServiceSummary,
			&i.WorkerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoice = `-- name: UpdateInvoice :one
UPDATE invoices
SET
    client_name         = COALESCE($2, client_name),
    client_address      = COALESCE($3, client_address),
    client_phone        = COALESCE($4, client_phone),
    service_name        = COALESCE($5, service_name),
    service_description = COALESCE($6, service_description),
    subtotal            = COALESCE($7, subtotal),
    total               = COALESCE($8, total),
    notes               = COALESCE($9, notes),
    status              = COALESCE($10, status),
    vendor_commission   = COALESCE($11, vendor_commission),
    updated_at          = NOW()
WHERE id = $1
RETURNING id, invoice_number, request_id, client_id, client_name, client_address, client_phone, service_name, service_description, discount, subtotal, total, notes, status, created_at, updated_at, vendor_commission
`

type UpdateInvoiceParams struct {
	ID                 uuid.UUID      `db:"id" json:"id"`
	ClientName         *string        `db:"client_name" json:"client_name"`
	ClientAddress      *string        `db:"client_address" json:"client_address"`
	ClientPhone        *string        `db:"client_phone" json:"client_phone"`
	ServiceName        *string        `db:"service_name" json:"service_name"`
	ServiceDescription *string        `db:"service_description" json:"service_description"`
	Subtotal           pgtype.Numeric `db:"subtotal" json:"subtotal"`
	Total              pgtype.Numeric `db:"total" json:"total"`
	Notes              *string        `db:"notes" json:"notes"`
	Status             *string        `db:"status" json:"status"`
	VendorCommission   pgtype.Numeric `db:"vendor_commission" json:"vendor_commission"`
}

func (q *Queries) UpdateInvoice(ctx context.Context, arg UpdateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, updateInvoice,
		arg.ID,
		arg.ClientName,
		arg.ClientAddress,
		arg.ClientPhone,
		arg.ServiceName,
		arg.ServiceDescription,
		arg.Subtotal,
		arg.Total,
		arg.Notes,
		arg.Status,
		arg.VendorCommission,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.RequestID,
		&i.ClientID,
		&i.ClientName,
		&i.ClientAddress,
		&i.ClientPhone,
		&i.ServiceName,
		&i.ServiceDescription,
		&i.Discount,
		&i.Subtotal,
		&i.Total,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VendorCommission,
	)
	return i, err
}
