// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountTransaction struct {
	ID              uuid.UUID      `db:"id" json:"id"`
	AccountID       uuid.UUID      `db:"account_id" json:"account_id"`
	TransactionType string         `db:"transaction_type" json:"transaction_type"`
	Amount          pgtype.Numeric `db:"amount" json:"amount"`
	Description     string         `db:"description" json:"description"`
	ReferenceType   *string        `db:"reference_type" json:"reference_type"`
	ReferenceID     pgtype.UUID    `db:"reference_id" json:"reference_id"`
	CreatedAt       time.Time      `db:"created_at" json:"created_at"`
}

type AdvanceDeduction struct {
	ID             uuid.UUID      `db:"id" json:"id"`
	AdvanceID      uuid.UUID      `db:"advance_id" json:"advance_id"`
	PayrollID      uuid.UUID      `db:"payroll_id" json:"payroll_id"`
	AmountDeducted pgtype.Numeric `db:"amount_deducted" json:"amount_deducted"`
	DeductedAt     time.Time      `db:"deducted_at" json:"deducted_at"`
}

type AuditLog struct {
	ID         uuid.UUID   `db:"id" json:"id"`
	Action     string      `db:"action" json:"action"`
	ActorID    pgtype.UUID `db:"actor_id" json:"actor_id"`
	ActorEmail *string     `db:"actor_email" json:"actor_email"`
	EntityType string      `db:"entity_type" json:"entity_type"`
	EntityID   pgtype.UUID `db:"entity_id" json:"entity_id"`
	Details    []byte      `db:"details" json:"details"`
	CreatedAt  time.Time   `db:"created_at" json:"created_at"`
}

type Expense struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	Date        time.Time      `db:"date" json:"date"`
	Description string         `db:"description" json:"description"`
	Category    string         `db:"category" json:"category"`
	Amount      pgtype.Numeric `db:"amount" json:"amount"`
	VendorPayee *string        `db:"vendor_payee" json:"vendor_payee"`
	ReceiptUrl  *string        `db:"receipt_url" json:"receipt_url"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at"`
}

type Income struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	Date        time.Time      `db:"date" json:"date"`
	Description string         `db:"description" json:"description"`
	Category    string         `db:"category" json:"category"`
	Amount      pgtype.Numeric `db:"amount" json:"amount"`
	Source      *string        `db:"source" json:"source"`
	ReceiptUrl  *string        `db:"receipt_url" json:"receipt_url"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at"`
	InvoiceID   pgtype.UUID    `db:"invoice_id" json:"invoice_id"`
}

type Inventory struct {
	ID                uuid.UUID      `db:"id" json:"id"`
	Name              string         `db:"name" json:"name"`
	Category          string         `db:"category" json:"category"`
	Quantity          int32          `db:"quantity" json:"quantity"`
	Unit              string         `db:"unit" json:"unit"`
	Condition         string         `db:"condition" json:"condition"`
	AssignedWorkerID  pgtype.UUID    `db:"assigned_worker_id" json:"assigned_worker_id"`
	PurchaseDate      pgtype.Date    `db:"purchase_date" json:"purchase_date"`
	Cost              pgtype.Numeric `db:"cost" json:"cost"`
	LowStockThreshold int32          `db:"low_stock_threshold" json:"low_stock_threshold"`
	CreatedAt         time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time      `db:"updated_at" json:"updated_at"`
}

type Invoice struct {
	ID                 uuid.UUID      `db:"id" json:"id"`
	InvoiceNumber      string         `db:"invoice_number" json:"invoice_number"`
	RequestID          pgtype.UUID    `db:"request_id" json:"request_id"`
	ClientID           uuid.UUID      `db:"client_id" json:"client_id"`
	ClientName         string         `db:"client_name" json:"client_name"`
	ClientAddress      *string        `db:"client_address" json:"client_address"`
	ClientPhone        *string        `db:"client_phone" json:"client_phone"`
	ServiceName        string         `db:"service_name" json:"service_name"`
	ServiceDescription *string        `db:"service_description" json:"service_description"`
	Discount           pgtype.Numeric `db:"discount" json:"discount"`
	Subtotal           pgtype.Numeric `db:"subtotal" json:"subtotal"`
	Total              pgtype.Numeric `db:"total" json:"total"`
	Notes              *string        `db:"notes" json:"notes"`
	Status             string         `db:"status" json:"status"`
	CreatedAt          time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt          time.Time      `db:"updated_at" json:"updated_at"`
	VendorCommission   pgtype.Numeric `db:"vendor_commission" json:"vendor_commission"`
}

type InvoiceCommission struct {
	ID        uuid.UUID      `db:"id" json:"id"`
	InvoiceID uuid.UUID      `db:"invoice_id" json:"invoice_id"`
	WorkerID  uuid.UUID      `db:"worker_id" json:"worker_id"`
	Amount    pgtype.Numeric `db:"amount" json:"amount"`
	CreatedAt time.Time      `db:"created_at" json:"created_at"`
	CreatedBy pgtype.UUID    `db:"created_by" json:"created_by"`
}

type InvoiceLineItem struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	InvoiceID   uuid.UUID      `db:"invoice_id" json:"invoice_id"`
	Description string         `db:"description" json:"description"`
	Quantity    pgtype.Numeric `db:"quantity" json:"quantity"`
	Rate        pgtype.Numeric `db:"rate" json:"rate"`
	Amount      pgtype.Numeric `db:"amount" json:"amount"`
}

type RequestImage struct {
	ID        uuid.UUID `db:"id" json:"id"`
	RequestID uuid.UUID `db:"request_id" json:"request_id"`
	Url       string    `db:"url" json:"url"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type RequestLineItem struct {
	ID        uuid.UUID `db:"id" json:"id"`
	RequestID uuid.UUID `db:"request_id" json:"request_id"`
	ServiceID uuid.UUID `db:"service_id" json:"service_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type RequestVendor struct {
	ID        uuid.UUID `db:"id" json:"id"`
	RequestID uuid.UUID `db:"request_id" json:"request_id"`
	VendorID  uuid.UUID `db:"vendor_id" json:"vendor_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type RequestWorker struct {
	RequestID  uuid.UUID   `db:"request_id" json:"request_id"`
	WorkerID   uuid.UUID   `db:"worker_id" json:"worker_id"`
	AssignedAt time.Time   `db:"assigned_at" json:"assigned_at"`
	AssignedBy pgtype.UUID `db:"assigned_by" json:"assigned_by"`
}

type SalaryPayment struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	WorkerID                 uuid.UUID          `db:"worker_id" json:"worker_id"`
	Month                    int32              `db:"month" json:"month"`
	Year                     int32              `db:"year" json:"year"`
	BaseAmount               pgtype.Numeric     `db:"base_amount" json:"base_amount"`
	JobsCount                int32              `db:"jobs_count" json:"jobs_count"`
	CommissionEarned         pgtype.Numeric     `db:"commission_earned" json:"commission_earned"`
	Deductions               pgtype.Numeric     `db:"deductions" json:"deductions"`
	NetPayable               pgtype.Numeric     `db:"net_payable" json:"net_payable"`
	Status                   string             `db:"status" json:"status"`
	PaidAt                   pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	CreatedAt                time.Time          `db:"created_at" json:"created_at"`
	CommissionPaidThisMonth  pgtype.Numeric     `db:"commission_paid_this_month" json:"commission_paid_this_month"`
	AdvanceDeductedThisMonth pgtype.Numeric     `db:"advance_deducted_this_month" json:"advance_deducted_this_month"`
}

type Service struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	Name          string      `db:"name" json:"name"`
	Description   string      `db:"description" json:"description"`
	Icon          string      `db:"icon" json:"icon"`
	CreatedAt     time.Time   `db:"created_at" json:"created_at"`
	ParentID      pgtype.UUID `db:"parent_id" json:"parent_id"`
	IsSubcategory bool        `db:"is_subcategory" json:"is_subcategory"`
}

type ServiceRequest struct {
	ID               uuid.UUID   `db:"id" json:"id"`
	RequestNumber    string      `db:"request_number" json:"request_number"`
	ClientID         uuid.UUID   `db:"client_id" json:"client_id"`
	ServiceID        uuid.UUID   `db:"service_id" json:"service_id"`
	Description      string      `db:"description" json:"description"`
	PreferredDate    time.Time   `db:"preferred_date" json:"preferred_date"`
	PreferredTime    string      `db:"preferred_time" json:"preferred_time"`
	Urgency          string      `db:"urgency" json:"urgency"`
	FullName         string      `db:"full_name" json:"full_name"`
	Phone            string      `db:"phone" json:"phone"`
	Email            string      `db:"email" json:"email"`
	Address          string      `db:"address" json:"address"`
	City             string      `db:"city" json:"city"`
	Area             string      `db:"area" json:"area"`
	Status           string      `db:"status" json:"status"`
	AssignedWorkerID pgtype.UUID `db:"assigned_worker_id" json:"assigned_worker_id"`
	InternalNotes    *string     `db:"internal_notes" json:"internal_notes"`
	CreatedAt        time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time   `db:"updated_at" json:"updated_at"`
	VendorID         pgtype.UUID `db:"vendor_id" json:"vendor_id"`
}

type SystemAccount struct {
	ID             uuid.UUID      `db:"id" json:"id"`
	Name           string         `db:"name" json:"name"`
	CurrentBalance pgtype.Numeric `db:"current_balance" json:"current_balance"`
	CreatedAt      time.Time      `db:"created_at" json:"created_at"`
}

type User struct {
	ID           uuid.UUID `db:"id" json:"id"`
	Name         string    `db:"name" json:"name"`
	Email        string    `db:"email" json:"email"`
	PasswordHash string    `db:"password_hash" json:"password_hash"`
	Role         string    `db:"role" json:"role"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time `db:"updated_at" json:"updated_at"`
}

type Vendor struct {
	ID              uuid.UUID `db:"id" json:"id"`
	Name            string    `db:"name" json:"name"`
	ContactName     *string   `db:"contact_name" json:"contact_name"`
	ContactPhone    string    `db:"contact_phone" json:"contact_phone"`
	ContactEmail    *string   `db:"contact_email" json:"contact_email"`
	ServicesOffered []string  `db:"services_offered" json:"services_offered"`
	Status          string    `db:"status" json:"status"`
	Notes           *string   `db:"notes" json:"notes"`
	CreatedAt       time.Time `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time `db:"updated_at" json:"updated_at"`
}

type Worker struct {
	ID                uuid.UUID      `db:"id" json:"id"`
	Name              string         `db:"name" json:"name"`
	Phone             string         `db:"phone" json:"phone"`
	Cnic              *string        `db:"cnic" json:"cnic"`
	Trades            []string       `db:"trades" json:"trades"`
	CompensationType  string         `db:"compensation_type" json:"compensation_type"`
	MonthlySalary     pgtype.Numeric `db:"monthly_salary" json:"monthly_salary"`
	CommissionPct     pgtype.Numeric `db:"commission_pct" json:"commission_pct"`
	MinGuarantee      pgtype.Numeric `db:"min_guarantee" json:"min_guarantee"`
	AvailabilityDays  []int32        `db:"availability_days" json:"availability_days"`
	AvailabilityStart pgtype.Time    `db:"availability_start" json:"availability_start"`
	AvailabilityEnd   pgtype.Time    `db:"availability_end" json:"availability_end"`
	Status            string         `db:"status" json:"status"`
	Notes             *string        `db:"notes" json:"notes"`
	CreatedAt         time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time      `db:"updated_at" json:"updated_at"`
}

type WorkerAdvance struct {
	ID                uuid.UUID      `db:"id" json:"id"`
	WorkerID          uuid.UUID      `db:"worker_id" json:"worker_id"`
	Amount            pgtype.Numeric `db:"amount" json:"amount"`
	Reason            *string        `db:"reason" json:"reason"`
	DateGiven         time.Time      `db:"date_given" json:"date_given"`
	TotalInstallments int32          `db:"total_installments" json:"total_installments"`
	InstallmentAmount pgtype.Numeric `db:"installment_amount" json:"installment_amount"`
	RemainingAmount   pgtype.Numeric `db:"remaining_amount" json:"remaining_amount"`
	Status            string         `db:"status" json:"status"`
	CreatedAt         time.Time      `db:"created_at" json:"created_at"`
}

type WorkerCommission struct {
	ID        uuid.UUID      `db:"id" json:"id"`
	WorkerID  uuid.UUID      `db:"worker_id" json:"worker_id"`
	InvoiceID uuid.UUID      `db:"invoice_id" json:"invoice_id"`
	Amount    pgtype.Numeric `db:"amount" json:"amount"`
	Status    string         `db:"status" json:"status"`
	PaidAt    time.Time      `db:"paid_at" json:"paid_at"`
	CreatedAt time.Time      `db:"created_at" json:"created_at"`
}
