// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: payroll.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPayrollByID = `-- name: GetPayrollByID :one
SELECT sp.id, sp.worker_id, sp.month, sp.year, sp.base_amount, sp.jobs_count, sp.commission_earned, sp.deductions, sp.net_payable, sp.status, sp.paid_at, sp.created_at, sp.commission_paid_this_month, sp.advance_deducted_this_month, w.name AS worker_name, w.compensation_type
FROM salary_payments sp
JOIN workers w ON w.id = sp.worker_id
WHERE sp.id = $1
`

type GetPayrollByIDRow struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	WorkerID                 uuid.UUID          `db:"worker_id" json:"worker_id"`
	Month                    int32              `db:"month" json:"month"`
	Year                     int32              `db:"year" json:"year"`
	BaseAmount               pgtype.Numeric     `db:"base_amount" json:"base_amount"`
	JobsCount                int32              `db:"jobs_count" json:"jobs_count"`
	CommissionEarned         pgtype.Numeric     `db:"commission_earned" json:"commission_earned"`
	Deductions               pgtype.Numeric     `db:"deductions" json:"deductions"`
	NetPayable               pgtype.Numeric     `db:"net_payable" json:"net_payable"`
	Status                   string             `db:"status" json:"status"`
	PaidAt                   pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	CreatedAt                time.Time          `db:"created_at" json:"created_at"`
	CommissionPaidThisMonth  pgtype.Numeric     `db:"commission_paid_this_month" json:"commission_paid_this_month"`
	AdvanceDeductedThisMonth pgtype.Numeric     `db:"advance_deducted_this_month" json:"advance_deducted_this_month"`
	WorkerName               string             `db:"worker_name" json:"worker_name"`
	CompensationType         string             `db:"compensation_type" json:"compensation_type"`
}

func (q *Queries) GetPayrollByID(ctx context.Context, id uuid.UUID) (GetPayrollByIDRow, error) {
	row := q.db.QueryRow(ctx, getPayrollByID, id)
	var i GetPayrollByIDRow
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.Month,
		&i.Year,
		&i.BaseAmount,
		&i.JobsCount,
		&i.CommissionEarned,
		&i.Deductions,
		&i.NetPayable,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.CommissionPaidThisMonth,
		&i.AdvanceDeductedThisMonth,
		&i.WorkerName,
		&i.CompensationType,
	)
	return i, err
}

const listPayroll = `-- name: ListPayroll :many
SELECT sp.id, sp.worker_id, sp.month, sp.year, sp.base_amount, sp.jobs_count, sp.commission_earned, sp.deductions, sp.net_payable, sp.status, sp.paid_at, sp.created_at, sp.commission_paid_this_month, sp.advance_deducted_this_month, w.name AS worker_name, w.compensation_type
FROM salary_payments sp
JOIN workers w ON w.id = sp.worker_id
WHERE ($1::integer IS NULL OR sp.month = $1)
  AND ($2::integer IS NULL OR sp.year  = $2)
ORDER BY w.name ASC
`

type ListPayrollParams struct {
	Column1 int32 `db:"column_1" json:"column_1"`
	Column2 int32 `db:"column_2" json:"column_2"`
}

type ListPayrollRow struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	WorkerID                 uuid.UUID          `db:"worker_id" json:"worker_id"`
	Month                    int32              `db:"month" json:"month"`
	Year                     int32              `db:"year" json:"year"`
	BaseAmount               pgtype.Numeric     `db:"base_amount" json:"base_amount"`
	JobsCount                int32              `db:"jobs_count" json:"jobs_count"`
	CommissionEarned         pgtype.Numeric     `db:"commission_earned" json:"commission_earned"`
	Deductions               pgtype.Numeric     `db:"deductions" json:"deductions"`
	NetPayable               pgtype.Numeric     `db:"net_payable" json:"net_payable"`
	Status                   string             `db:"status" json:"status"`
	PaidAt                   pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	CreatedAt                time.Time          `db:"created_at" json:"created_at"`
	CommissionPaidThisMonth  pgtype.Numeric     `db:"commission_paid_this_month" json:"commission_paid_this_month"`
	AdvanceDeductedThisMonth pgtype.Numeric     `db:"advance_deducted_this_month" json:"advance_deducted_this_month"`
	WorkerName               string             `db:"worker_name" json:"worker_name"`
	CompensationType         string             `db:"compensation_type" json:"compensation_type"`
}

func (q *Queries) ListPayroll(ctx context.Context, arg ListPayrollParams) ([]ListPayrollRow, error) {
	rows, err := q.db.Query(ctx, listPayroll, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPayrollRow{}
	for rows.Next() {
		var i ListPayrollRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkerID,
			&i.Month,
			&i.Year,
			&i.BaseAmount,
			&i.JobsCount,
			&i.CommissionEarned,
			&i.Deductions,
			&i.NetPayable,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
			&i.CommissionPaidThisMonth,
			&i.AdvanceDeductedThisMonth,
			&i.WorkerName,
			&i.CompensationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingPayrollForMonth = `-- name: ListPendingPayrollForMonth :many
SELECT sp.id, sp.worker_id, sp.month, sp.year, sp.base_amount, sp.jobs_count, sp.commission_earned, sp.deductions, sp.net_payable, sp.status, sp.paid_at, sp.created_at, sp.commission_paid_this_month, sp.advance_deducted_this_month, w.name AS worker_name, w.compensation_type
FROM salary_payments sp
JOIN workers w ON w.id = sp.worker_id
WHERE sp.month = $1 AND sp.year = $2 AND sp.status = 'pending'
ORDER BY w.name ASC
`

type ListPendingPayrollForMonthParams struct {
	Month int32 `db:"month" json:"month"`
	Year  int32 `db:"year" json:"year"`
}

type ListPendingPayrollForMonthRow struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	WorkerID                 uuid.UUID          `db:"worker_id" json:"worker_id"`
	Month                    int32              `db:"month" json:"month"`
	Year                     int32              `db:"year" json:"year"`
	BaseAmount               pgtype.Numeric     `db:"base_amount" json:"base_amount"`
	JobsCount                int32              `db:"jobs_count" json:"jobs_count"`
	CommissionEarned         pgtype.Numeric     `db:"commission_earned" json:"commission_earned"`
	Deductions               pgtype.Numeric     `db:"deductions" json:"deductions"`
	NetPayable               pgtype.Numeric     `db:"net_payable" json:"net_payable"`
	Status                   string             `db:"status" json:"status"`
	PaidAt                   pgtype.Timestamptz `db:"paid_at" json:"paid_at"`
	CreatedAt                time.Time          `db:"created_at" json:"created_at"`
	CommissionPaidThisMonth  pgtype.Numeric     `db:"commission_paid_this_month" json:"commission_paid_this_month"`
	AdvanceDeductedThisMonth pgtype.Numeric     `db:"advance_deducted_this_month" json:"advance_deducted_this_month"`
	WorkerName               string             `db:"worker_name" json:"worker_name"`
	CompensationType         string             `db:"compensation_type" json:"compensation_type"`
}

func (q *Queries) ListPendingPayrollForMonth(ctx context.Context, arg ListPendingPayrollForMonthParams) ([]ListPendingPayrollForMonthRow, error) {
	rows, err := q.db.Query(ctx, listPendingPayrollForMonth, arg.Month, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingPayrollForMonthRow{}
	for rows.Next() {
		var i ListPendingPayrollForMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkerID,
			&i.Month,
			&i.Year,
			&i.BaseAmount,
			&i.JobsCount,
			&i.CommissionEarned,
			&i.Deductions,
			&i.NetPayable,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
			&i.CommissionPaidThisMonth,
			&i.AdvanceDeductedThisMonth,
			&i.WorkerName,
			&i.CompensationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllPayrollPaidForMonth = `-- name: MarkAllPayrollPaidForMonth :exec
UPDATE salary_payments
SET status = 'paid', paid_at = NOW()
WHERE month = $1 AND year = $2 AND status = 'pending'
`

type MarkAllPayrollPaidForMonthParams struct {
	Month int32 `db:"month" json:"month"`
	Year  int32 `db:"year" json:"year"`
}

func (q *Queries) MarkAllPayrollPaidForMonth(ctx context.Context, arg MarkAllPayrollPaidForMonthParams) error {
	_, err := q.db.Exec(ctx, markAllPayrollPaidForMonth, arg.Month, arg.Year)
	return err
}

const markPayrollPaid = `-- name: MarkPayrollPaid :one
UPDATE salary_payments
SET status = 'paid', paid_at = NOW()
WHERE id = $1
RETURNING id, worker_id, month, year, base_amount, jobs_count, commission_earned, deductions, net_payable, status, paid_at, created_at, commission_paid_this_month, advance_deducted_this_month
`

func (q *Queries) MarkPayrollPaid(ctx context.Context, id uuid.UUID) (SalaryPayment, error) {
	row := q.db.QueryRow(ctx, markPayrollPaid, id)
	var i SalaryPayment
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.Month,
		&i.Year,
		&i.BaseAmount,
		&i.JobsCount,
		&i.CommissionEarned,
		&i.Deductions,
		&i.NetPayable,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.CommissionPaidThisMonth,
		&i.AdvanceDeductedThisMonth,
	)
	return i, err
}

const updatePayroll = `-- name: UpdatePayroll :one
UPDATE salary_payments
SET
    base_amount                 = COALESCE($2, base_amount),
    jobs_count                  = COALESCE($3, jobs_count),
    commission_earned           = COALESCE($4, commission_earned),
    deductions                  = COALESCE($5, deductions),
    net_payable                 = COALESCE($6, net_payable),
    status                      = COALESCE($7, status),
    commission_paid_this_month  = COALESCE($8, commission_paid_this_month),
    advance_deducted_this_month = COALESCE($9, advance_deducted_this_month),
    paid_at                     = CASE
                                    WHEN $7::text = 'pending' THEN NULL
                                    WHEN $7::text = 'paid' AND paid_at IS NULL THEN NOW()
                                    ELSE paid_at
                                END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, worker_id, month, year, base_amount, jobs_count, commission_earned, deductions, net_payable, status, paid_at, created_at, commission_paid_this_month, advance_deducted_this_month
`

type UpdatePayrollParams struct {
	ID                       uuid.UUID      `db:"id" json:"id"`
	BaseAmount               pgtype.Numeric `db:"base_amount" json:"base_amount"`
	JobsCount                *int32         `db:"jobs_count" json:"jobs_count"`
	CommissionEarned         pgtype.Numeric `db:"commission_earned" json:"commission_earned"`
	Deductions               pgtype.Numeric `db:"deductions" json:"deductions"`
	NetPayable               pgtype.Numeric `db:"net_payable" json:"net_payable"`
	Status                   *string        `db:"status" json:"status"`
	CommissionPaidThisMonth  pgtype.Numeric `db:"commission_paid_this_month" json:"commission_paid_this_month"`
	AdvanceDeductedThisMonth pgtype.Numeric `db:"advance_deducted_this_month" json:"advance_deducted_this_month"`
}

func (q *Queries) UpdatePayroll(ctx context.Context, arg UpdatePayrollParams) (SalaryPayment, error) {
	row := q.db.QueryRow(ctx, updatePayroll,
		arg.ID,
		arg.BaseAmount,
		arg.JobsCount,
		arg.CommissionEarned,
		arg.Deductions,
		arg.NetPayable,
		arg.Status,
		arg.CommissionPaidThisMonth,
		arg.AdvanceDeductedThisMonth,
	)
	var i SalaryPayment
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.Month,
		&i.Year,
		&i.BaseAmount,
		&i.JobsCount,
		&i.CommissionEarned,
		&i.Deductions,
		&i.NetPayable,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.CommissionPaidThisMonth,
		&i.AdvanceDeductedThisMonth,
	)
	return i, err
}

const upsertSalaryPayment = `-- name: UpsertSalaryPayment :one
INSERT INTO salary_payments (
    worker_id, month, year, base_amount, jobs_count,
    commission_earned, deductions, net_payable, status,
    commission_paid_this_month, advance_deducted_this_month
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (worker_id, month, year)
DO UPDATE SET
    base_amount                 = EXCLUDED.base_amount,
    jobs_count                  = EXCLUDED.jobs_count,
    commission_earned           = EXCLUDED.commission_earned,
    deductions                  = EXCLUDED.deductions,
    net_payable                 = EXCLUDED.net_payable,
    status                      = EXCLUDED.status,
    commission_paid_this_month  = EXCLUDED.commission_paid_this_month,
    advance_deducted_this_month = EXCLUDED.advance_deducted_this_month
RETURNING id, worker_id, month, year, base_amount, jobs_count, commission_earned, deductions, net_payable, status, paid_at, created_at, commission_paid_this_month, advance_deducted_this_month
`

type UpsertSalaryPaymentParams struct {
	WorkerID                 uuid.UUID      `db:"worker_id" json:"worker_id"`
	Month                    int32          `db:"month" json:"month"`
	Year                     int32          `db:"year" json:"year"`
	BaseAmount               pgtype.Numeric `db:"base_amount" json:"base_amount"`
	JobsCount                int32          `db:"jobs_count" json:"jobs_count"`
	CommissionEarned         pgtype.Numeric `db:"commission_earned" json:"commission_earned"`
	Deductions               pgtype.Numeric `db:"deductions" json:"deductions"`
	NetPayable               pgtype.Numeric `db:"net_payable" json:"net_payable"`
	Status                   string         `db:"status" json:"status"`
	CommissionPaidThisMonth  pgtype.Numeric `db:"commission_paid_this_month" json:"commission_paid_this_month"`
	AdvanceDeductedThisMonth pgtype.Numeric `db:"advance_deducted_this_month" json:"advance_deducted_this_month"`
}

func (q *Queries) UpsertSalaryPayment(ctx context.Context, arg UpsertSalaryPaymentParams) (SalaryPayment, error) {
	row := q.db.QueryRow(ctx, upsertSalaryPayment,
		arg.WorkerID,
		arg.Month,
		arg.Year,
		arg.BaseAmount,
		arg.JobsCount,
		arg.CommissionEarned,
		arg.Deductions,
		arg.NetPayable,
		arg.Status,
		arg.CommissionPaidThisMonth,
		arg.AdvanceDeductedThisMonth,
	)
	var i SalaryPayment
	err := row.Scan(
		&i.ID,
		&i.WorkerID,
		&i.Month,
		&i.Year,
		&i.BaseAmount,
		&i.JobsCount,
		&i.CommissionEarned,
		&i.Deductions,
		&i.NetPayable,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.CommissionPaidThisMonth,
		&i.AdvanceDeductedThisMonth,
	)
	return i, err
}
