// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: requests.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearRequestVendor = `-- name: ClearRequestVendor :one
UPDATE service_requests
SET vendor_id = NULL, updated_at = NOW()
WHERE id = $1
RETURNING id, request_number, client_id, service_id, description, preferred_date, preferred_time, urgency, full_name, phone, email, address, city, area, status, assigned_worker_id, internal_notes, created_at, updated_at, vendor_id
`

func (q *Queries) ClearRequestVendor(ctx context.Context, id uuid.UUID) (ServiceRequest, error) {
	row := q.db.QueryRow(ctx, clearRequestVendor, id)
	var i ServiceRequest
	err := row.Scan(
		&i.ID,
		&i.RequestNumber,
		&i.ClientID,
		&i.ServiceID,
		&i.Description,
		&i.PreferredDate,
		&i.PreferredTime,
		&i.Urgency,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.City,
		&i.Area,
		&i.Status,
		&i.AssignedWorkerID,
		&i.InternalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VendorID,
	)
	return i, err
}

const countActiveRequests = `-- name: CountActiveRequests :one
SELECT COUNT(*) FROM service_requests
WHERE status IN ('pending', 'assigned', 'in_progress')
`

func (q *Queries) CountActiveRequests(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveRequests)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllRequests = `-- name: CountAllRequests :one
SELECT COUNT(*)
FROM service_requests sr
JOIN users u ON u.id = sr.client_id
WHERE
    ($1::text IS NULL OR $1 = '' OR sr.status     = $1) AND
    ($2::text IS NULL OR $2 = '' OR sr.urgency    = $2) AND
    ($3::uuid IS NULL OR $3 = '00000000-0000-0000-0000-000000000000' OR sr.service_id = $3) AND
    ($4::text IS NULL OR $4 = '' OR
        u.name ILIKE '%' || $4 || '%' OR
        sr.request_number ILIKE '%' || $4 || '%'
    )                                        AND
    ($5::date IS NULL OR $5 = '0001-01-01' OR sr.created_at::date >= $5) AND
    ($6::date IS NULL OR $6 = '0001-01-01' OR sr.created_at::date <= $6)
`

type CountAllRequestsParams struct {
	Column1 string    `db:"column_1" json:"column_1"`
	Column2 string    `db:"column_2" json:"column_2"`
	Column3 uuid.UUID `db:"column_3" json:"column_3"`
	Column4 string    `db:"column_4" json:"column_4"`
	Column5 time.Time `db:"column_5" json:"column_5"`
	Column6 time.Time `db:"column_6" json:"column_6"`
}

func (q *Queries) CountAllRequests(ctx context.Context, arg CountAllRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAllRequests,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequestsByClient = `-- name: CountRequestsByClient :one
SELECT COUNT(*) FROM service_requests WHERE client_id = $1
`

func (q *Queries) CountRequestsByClient(ctx context.Context, clientID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestsByClient, clientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequestsInRange = `-- name: CountRequestsInRange :one
SELECT COUNT(*) FROM service_requests
WHERE
    ($1::date IS NULL OR created_at::date >= $1) AND
    ($2::date IS NULL OR created_at::date <= $2)
`

type CountRequestsInRangeParams struct {
	Column1 time.Time `db:"column_1" json:"column_1"`
	Column2 time.Time `db:"column_2" json:"column_2"`
}

func (q *Queries) CountRequestsInRange(ctx context.Context, arg CountRequestsInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestsInRange, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequestsToday = `-- name: CountRequestsToday :one
SELECT COUNT(*) FROM service_requests
WHERE created_at >= CURRENT_DATE AND created_at < CURRENT_DATE + INTERVAL '1 day'
`

func (q *Queries) CountRequestsToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestsToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRequest = `-- name: CreateRequest :one
INSERT INTO service_requests (
    request_number, client_id, service_id, description,
    preferred_date, preferred_time, urgency,
    full_name, phone, email, address, city, area
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, request_number, client_id, service_id, description, preferred_date, preferred_time, urgency, full_name, phone, email, address, city, area, status, assigned_worker_id, internal_notes, created_at, updated_at, vendor_id
`

type CreateRequestParams struct {
	RequestNumber string    `db:"request_number" json:"request_number"`
	ClientID      uuid.UUID `db:"client_id" json:"client_id"`
	ServiceID     uuid.UUID `db:"service_id" json:"service_id"`
	Description   string    `db:"description" json:"description"`
	PreferredDate time.Time `db:"preferred_date" json:"preferred_date"`
	PreferredTime string    `db:"preferred_time" json:"preferred_time"`
	Urgency       string    `db:"urgency" json:"urgency"`
	FullName      string    `db:"full_name" json:"full_name"`
	Phone         string    `db:"phone" json:"phone"`
	Email         string    `db:"email" json:"email"`
	Address       string    `db:"address" json:"address"`
	City          string    `db:"city" json:"city"`
	Area          string    `db:"area" json:"area"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (ServiceRequest, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.RequestNumber,
		arg.ClientID,
		arg.ServiceID,
		arg.Description,
		arg.PreferredDate,
		arg.PreferredTime,
		arg.Urgency,
		arg.FullName,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.City,
		arg.Area,
	)
	var i ServiceRequest
	err := row.Scan(
		&i.ID,
		&i.RequestNumber,
		&i.ClientID,
		&i.ServiceID,
		&i.Description,
		&i.PreferredDate,
		&i.PreferredTime,
		&i.Urgency,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.City,
		&i.Area,
		&i.Status,
		&i.AssignedWorkerID,
		&i.InternalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VendorID,
	)
	return i, err
}

const createRequestImage = `-- name: CreateRequestImage :one
INSERT INTO request_images (request_id, url) VALUES ($1, $2) RETURNING id, request_id, url, created_at
`

type CreateRequestImageParams struct {
	RequestID uuid.UUID `db:"request_id" json:"request_id"`
	Url       string    `db:"url" json:"url"`
}

func (q *Queries) CreateRequestImage(ctx context.Context, arg CreateRequestImageParams) (RequestImage, error) {
	row := q.db.QueryRow(ctx, createRequestImage, arg.RequestID, arg.Url)
	var i RequestImage
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const createRequestLineItem = `-- name: CreateRequestLineItem :one
INSERT INTO request_line_items (request_id, service_id) VALUES ($1, $2) RETURNING id, request_id, service_id, created_at
`

type CreateRequestLineItemParams struct {
	RequestID uuid.UUID `db:"request_id" json:"request_id"`
	ServiceID uuid.UUID `db:"service_id" json:"service_id"`
}

func (q *Queries) CreateRequestLineItem(ctx context.Context, arg CreateRequestLineItemParams) (RequestLineItem, error) {
	row := q.db.QueryRow(ctx, createRequestLineItem, arg.RequestID, arg.ServiceID)
	var i RequestLineItem
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ServiceID,
		&i.CreatedAt,
	)
	return i, err
}

const getRecentRequests = `-- name: GetRecentRequests :many
SELECT
    sr.id, sr.request_number, sr.client_id, sr.service_id, sr.description, sr.preferred_date, sr.preferred_time, sr.urgency, sr.full_name, sr.phone, sr.email, sr.address, sr.city, sr.area, sr.status, sr.assigned_worker_id, sr.internal_notes, sr.created_at, sr.updated_at, sr.vendor_id,
    s.name AS service_name,
    COALESCE(li.service_count, 1::bigint) AS service_count,
    COALESCE(li.service_summary, s.name) AS service_summary,
    u.name AS client_name,
    w.name AS worker_name
FROM service_requests sr
JOIN services s ON s.id = sr.service_id
LEFT JOIN (
    SELECT
        rli.request_id,
        COUNT(*)::bigint AS service_count,
        STRING_AGG(s2.name, ', ' ORDER BY rli.created_at) AS service_summary
    FROM request_line_items rli
    JOIN services s2 ON s2.id = rli.service_id
    GROUP BY rli.request_id
) li ON li.request_id = sr.id
JOIN users    u ON u.id = sr.client_id
LEFT JOIN workers w ON w.id = sr.assigned_worker_id
ORDER BY sr.created_at DESC
LIMIT $1
`

type GetRecentRequestsRow struct {
	ID               uuid.UUID   `db:"id" json:"id"`
	RequestNumber    string      `db:"request_number" json:"request_number"`
	ClientID         uuid.UUID   `db:"client_id" json:"client_id"`
	ServiceID        uuid.UUID   `db:"service_id" json:"service_id"`
	Description      string      `db:"description" json:"description"`
	PreferredDate    time.Time   `db:"preferred_date" json:"preferred_date"`
	PreferredTime    string      `db:"preferred_time" json:"preferred_time"`
	Urgency          string      `db:"urgency" json:"urgency"`
	FullName         string      `db:"full_name" json:"full_name"`
	Phone            string      `db:"phone" json:"phone"`
	Email            string      `db:"email" json:"email"`
	Address          string      `db:"address" json:"address"`
	City             string      `db:"city" json:"city"`
	Area             string      `db:"area" json:"area"`
	Status           string      `db:"status" json:"status"`
	AssignedWorkerID pgtype.UUID `db:"assigned_worker_id" json:"assigned_worker_id"`
	InternalNotes    *string     `db:"internal_notes" json:"internal_notes"`
	CreatedAt        time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time   `db:"updated_at" json:"updated_at"`
	VendorID         pgtype.UUID `db:"vendor_id" json:"vendor_id"`
	ServiceName      string      `db:"service_name" json:"service_name"`
	ServiceCount     int64       `db:"service_count" json:"service_count"`
	ServiceSummary   []byte      `db:"service_summary" json:"service_summary"`
	ClientName       string      `db:"client_name" json:"client_name"`
	WorkerName       *string     `db:"worker_name" json:"worker_name"`
}

func (q *Queries) GetRecentRequests(ctx context.Context, limit int32) ([]GetRecentRequestsRow, error) {
	rows, err := q.db.Query(ctx, getRecentRequests, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentRequestsRow{}
	for rows.Next() {
		var i GetRecentRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestNumber,
			&i.ClientID,
			&i.ServiceID,
			&i.Description,
			&i.PreferredDate,
			&i.PreferredTime,
			&i.Urgency,
			&i.FullName,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.City,
			&i.Area,
			&i.Status,
			&i.AssignedWorkerID,
			&i.InternalNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VendorID,
			&i.ServiceName,
			&i.ServiceCount,
			&i.ServiceSummary,
			&i.ClientName,
			&i.WorkerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentRequestsInRange = `-- name: GetRecentRequestsInRange :many
SELECT
    sr.id, sr.request_number, sr.client_id, sr.service_id, sr.description, sr.preferred_date, sr.preferred_time, sr.urgency, sr.full_name, sr.phone, sr.email, sr.address, sr.city, sr.area, sr.status, sr.assigned_worker_id, sr.internal_notes, sr.created_at, sr.updated_at, sr.vendor_id,
    s.name AS service_name,
    COALESCE(li.service_count, 1::bigint) AS service_count,
    COALESCE(li.service_summary, s.name) AS service_summary,
    u.name AS client_name,
    w.name AS worker_name
FROM service_requests sr
JOIN services s ON s.id = sr.service_id
LEFT JOIN (
    SELECT
        rli.request_id,
        COUNT(*)::bigint AS service_count,
        STRING_AGG(s2.name, ', ' ORDER BY rli.created_at) AS service_summary
    FROM request_line_items rli
    JOIN services s2 ON s2.id = rli.service_id
    GROUP BY rli.request_id
) li ON li.request_id = sr.id
JOIN users    u ON u.id = sr.client_id
LEFT JOIN workers w ON w.id = sr.assigned_worker_id
WHERE
    ($2::date IS NULL OR sr.created_at::date >= $2) AND
    ($3::date IS NULL OR sr.created_at::date <= $3)
ORDER BY sr.created_at DESC
LIMIT $1
`

type GetRecentRequestsInRangeParams struct {
	Limit   int32     `db:"limit" json:"limit"`
	Column2 time.Time `db:"column_2" json:"column_2"`
	Column3 time.Time `db:"column_3" json:"column_3"`
}

type GetRecentRequestsInRangeRow struct {
	ID               uuid.UUID   `db:"id" json:"id"`
	RequestNumber    string      `db:"request_number" json:"request_number"`
	ClientID         uuid.UUID   `db:"client_id" json:"client_id"`
	ServiceID        uuid.UUID   `db:"service_id" json:"service_id"`
	Description      string      `db:"description" json:"description"`
	PreferredDate    time.Time   `db:"preferred_date" json:"preferred_date"`
	PreferredTime    string      `db:"preferred_time" json:"preferred_time"`
	Urgency          string      `db:"urgency" json:"urgency"`
	FullName         string      `db:"full_name" json:"full_name"`
	Phone            string      `db:"phone" json:"phone"`
	Email            string      `db:"email" json:"email"`
	Address          string      `db:"address" json:"address"`
	City             string      `db:"city" json:"city"`
	Area             string      `db:"area" json:"area"`
	Status           string      `db:"status" json:"status"`
	AssignedWorkerID pgtype.UUID `db:"assigned_worker_id" json:"assigned_worker_id"`
	InternalNotes    *string     `db:"internal_notes" json:"internal_notes"`
	CreatedAt        time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time   `db:"updated_at" json:"updated_at"`
	VendorID         pgtype.UUID `db:"vendor_id" json:"vendor_id"`
	ServiceName      string      `db:"service_name" json:"service_name"`
	ServiceCount     int64       `db:"service_count" json:"service_count"`
	ServiceSummary   []byte      `db:"service_summary" json:"service_summary"`
	ClientName       string      `db:"client_name" json:"client_name"`
	WorkerName       *string     `db:"worker_name" json:"worker_name"`
}

func (q *Queries) GetRecentRequestsInRange(ctx context.Context, arg GetRecentRequestsInRangeParams) ([]GetRecentRequestsInRangeRow, error) {
	rows, err := q.db.Query(ctx, getRecentRequestsInRange, arg.Limit, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentRequestsInRangeRow{}
	for rows.Next() {
		var i GetRecentRequestsInRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestNumber,
			&i.ClientID,
			&i.ServiceID,
			&i.Description,
			&i.PreferredDate,
			&i.PreferredTime,
			&i.Urgency,
			&i.FullName,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.City,
			&i.Area,
			&i.Status,
			&i.AssignedWorkerID,
			&i.InternalNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VendorID,
			&i.ServiceName,
			&i.ServiceCount,
			&i.ServiceSummary,
			&i.ClientName,
			&i.WorkerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRequestByID = `-- name: GetRequestByID :one
SELECT
    sr.id, sr.request_number, sr.client_id, sr.service_id, sr.description, sr.preferred_date, sr.preferred_time, sr.urgency, sr.full_name, sr.phone, sr.email, sr.address, sr.city, sr.area, sr.status, sr.assigned_worker_id, sr.internal_notes, sr.created_at, sr.updated_at, sr.vendor_id,
    s.name  AS service_name,
    u.name  AS client_name,
    w.name  AS worker_name,
    w.phone AS worker_phone,
    v.id    AS vendor_id,
    v.name  AS vendor_name,
    v.contact_phone AS vendor_phone
FROM service_requests sr
JOIN services s ON s.id = sr.service_id
JOIN users    u ON u.id = sr.client_id
    LEFT JOIN workers w ON w.id = sr.assigned_worker_id
    LEFT JOIN vendors v ON v.id = sr.vendor_id
    WHERE sr.id = $1
`

type GetRequestByIDRow struct {
	ID               uuid.UUID   `db:"id" json:"id"`
	RequestNumber    string      `db:"request_number" json:"request_number"`
	ClientID         uuid.UUID   `db:"client_id" json:"client_id"`
	ServiceID        uuid.UUID   `db:"service_id" json:"service_id"`
	Description      string      `db:"description" json:"description"`
	PreferredDate    time.Time   `db:"preferred_date" json:"preferred_date"`
	PreferredTime    string      `db:"preferred_time" json:"preferred_time"`
	Urgency          string      `db:"urgency" json:"urgency"`
	FullName         string      `db:"full_name" json:"full_name"`
	Phone            string      `db:"phone" json:"phone"`
	Email            string      `db:"email" json:"email"`
	Address          string      `db:"address" json:"address"`
	City             string      `db:"city" json:"city"`
	Area             string      `db:"area" json:"area"`
	Status           string      `db:"status" json:"status"`
	AssignedWorkerID pgtype.UUID `db:"assigned_worker_id" json:"assigned_worker_id"`
	InternalNotes    *string     `db:"internal_notes" json:"internal_notes"`
	CreatedAt        time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time   `db:"updated_at" json:"updated_at"`
	VendorID         pgtype.UUID `db:"vendor_id" json:"vendor_id"`
	ServiceName      string      `db:"service_name" json:"service_name"`
	ClientName       string      `db:"client_name" json:"client_name"`
	WorkerName       *string     `db:"worker_name" json:"worker_name"`
	WorkerPhone      *string     `db:"worker_phone" json:"worker_phone"`
	VendorID_2       pgtype.UUID `db:"vendor_id_2" json:"vendor_id_2"`
	VendorName       *string     `db:"vendor_name" json:"vendor_name"`
	VendorPhone      *string     `db:"vendor_phone" json:"vendor_phone"`
}

func (q *Queries) GetRequestByID(ctx context.Context, id uuid.UUID) (GetRequestByIDRow, error) {
	row := q.db.QueryRow(ctx, getRequestByID, id)
	var i GetRequestByIDRow
	err := row.Scan(
		&i.ID,
		&i.RequestNumber,
		&i.ClientID,
		&i.ServiceID,
		&i.Description,
		&i.PreferredDate,
		&i.PreferredTime,
		&i.Urgency,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.City,
		&i.Area,
		&i.Status,
		&i.AssignedWorkerID,
		&i.InternalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VendorID,
		&i.ServiceName,
		&i.ClientName,
		&i.WorkerName,
		&i.WorkerPhone,
		&i.VendorID_2,
		&i.VendorName,
		&i.VendorPhone,
	)
	return i, err
}

const getServiceDistribution = `-- name: GetServiceDistribution :many
SELECT s.name AS service_name, COUNT(sr.id) AS request_count
FROM service_requests sr
JOIN services s ON s.id = sr.service_id
WHERE
    ($1::date IS NULL OR sr.created_at::date >= $1) AND
    ($2::date IS NULL OR sr.created_at::date <= $2)
GROUP BY s.name
ORDER BY request_count DESC
LIMIT 6
`

type GetServiceDistributionParams struct {
	Column1 time.Time `db:"column_1" json:"column_1"`
	Column2 time.Time `db:"column_2" json:"column_2"`
}

type GetServiceDistributionRow struct {
	ServiceName  string `db:"service_name" json:"service_name"`
	RequestCount int64  `db:"request_count" json:"request_count"`
}

func (q *Queries) GetServiceDistribution(ctx context.Context, arg GetServiceDistributionParams) ([]GetServiceDistributionRow, error) {
	rows, err := q.db.Query(ctx, getServiceDistribution, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetServiceDistributionRow{}
	for rows.Next() {
		var i GetServiceDistributionRow
		if err := rows.Scan(&i.ServiceName, &i.RequestCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRequests = `-- name: ListAllRequests :many
SELECT
    sr.id, sr.request_number, sr.client_id, sr.service_id, sr.description, sr.preferred_date, sr.preferred_time, sr.urgency, sr.full_name, sr.phone, sr.email, sr.address, sr.city, sr.area, sr.status, sr.assigned_worker_id, sr.internal_notes, sr.created_at, sr.updated_at, sr.vendor_id,
    s.name  AS service_name,
    COALESCE(li.service_count, 1::bigint) AS service_count,
    COALESCE(li.service_summary, s.name) AS service_summary,
    u.name  AS client_name,
    rw_agg.worker_names AS worker_names,
    sr.vendor_id AS vendor_id,
    v.name  AS vendor_name
FROM service_requests sr
JOIN services s ON s.id = sr.service_id
LEFT JOIN (
    SELECT
        rli.request_id,
        COUNT(*)::bigint AS service_count,
        STRING_AGG(s.name, ', ' ORDER BY rli.created_at) AS service_summary
    FROM request_line_items rli
    JOIN services s ON s.id = rli.service_id
    GROUP BY rli.request_id
) li ON li.request_id = sr.id
JOIN users    u ON u.id = sr.client_id
LEFT JOIN (
    SELECT
        rw.request_id,
        STRING_AGG(w.name, ', ' ORDER BY rw.assigned_at) AS worker_names
    FROM request_workers rw
    JOIN workers w ON w.id = rw.worker_id
    GROUP BY rw.request_id
) rw_agg ON rw_agg.request_id = sr.id
LEFT JOIN vendors v ON v.id = sr.vendor_id
WHERE
    ($1::text   IS NULL OR $1 = ''   OR sr.status     = $1)   AND
    ($2::text   IS NULL OR $2 = ''   OR sr.urgency    = $2)   AND
    ($3::uuid   IS NULL OR $3 = '00000000-0000-0000-0000-000000000000' OR sr.service_id = $3)   AND
    ($4::text   IS NULL OR $4 = ''   OR
        u.name  ILIKE '%' || $4 || '%' OR
        sr.request_number ILIKE '%' || $4 || '%'
    )                                            AND
    ($7::date   IS NULL OR $7 = '0001-01-01' OR sr.created_at::date >= $7) AND
    ($8::date   IS NULL OR $8 = '0001-01-01' OR sr.created_at::date <= $8) AND
    ($9::text   IS NULL OR $9 = '' OR $9 = 'all' OR
        ($9 = 'workers' AND sr.assigned_worker_id IS NOT NULL AND sr.vendor_id IS NULL) OR
        ($9 = 'vendors' AND sr.vendor_id IS NOT NULL) OR
        ($9 = 'unassigned' AND sr.assigned_worker_id IS NULL AND sr.vendor_id IS NULL AND NOT EXISTS (
            SELECT 1 FROM request_workers rw WHERE rw.request_id = sr.id
        ))
    )
ORDER BY sr.created_at DESC
LIMIT $5 OFFSET $6
`

type ListAllRequestsParams struct {
	Column1 string    `db:"column_1" json:"column_1"`
	Column2 string    `db:"column_2" json:"column_2"`
	Column3 uuid.UUID `db:"column_3" json:"column_3"`
	Column4 string    `db:"column_4" json:"column_4"`
	Limit   int32     `db:"limit" json:"limit"`
	Offset  int32     `db:"offset" json:"offset"`
	Column7 time.Time `db:"column_7" json:"column_7"`
	Column8 time.Time `db:"column_8" json:"column_8"`
	Column9 string    `db:"column_9" json:"column_9"`
}

type ListAllRequestsRow struct {
	ID               uuid.UUID   `db:"id" json:"id"`
	RequestNumber    string      `db:"request_number" json:"request_number"`
	ClientID         uuid.UUID   `db:"client_id" json:"client_id"`
	ServiceID        uuid.UUID   `db:"service_id" json:"service_id"`
	Description      string      `db:"description" json:"description"`
	PreferredDate    time.Time   `db:"preferred_date" json:"preferred_date"`
	PreferredTime    string      `db:"preferred_time" json:"preferred_time"`
	Urgency          string      `db:"urgency" json:"urgency"`
	FullName         string      `db:"full_name" json:"full_name"`
	Phone            string      `db:"phone" json:"phone"`
	Email            string      `db:"email" json:"email"`
	Address          string      `db:"address" json:"address"`
	City             string      `db:"city" json:"city"`
	Area             string      `db:"area" json:"area"`
	Status           string      `db:"status" json:"status"`
	AssignedWorkerID pgtype.UUID `db:"assigned_worker_id" json:"assigned_worker_id"`
	InternalNotes    *string     `db:"internal_notes" json:"internal_notes"`
	CreatedAt        time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time   `db:"updated_at" json:"updated_at"`
	VendorID         pgtype.UUID `db:"vendor_id" json:"vendor_id"`
	ServiceName      string      `db:"service_name" json:"service_name"`
	ServiceCount     int64       `db:"service_count" json:"service_count"`
	ServiceSummary   []byte      `db:"service_summary" json:"service_summary"`
	ClientName       string      `db:"client_name" json:"client_name"`
	WorkerNames      []byte      `db:"worker_names" json:"worker_names"`
	VendorID_2       pgtype.UUID `db:"vendor_id_2" json:"vendor_id_2"`
	VendorName       *string     `db:"vendor_name" json:"vendor_name"`
}

func (q *Queries) ListAllRequests(ctx context.Context, arg ListAllRequestsParams) ([]ListAllRequestsRow, error) {
	rows, err := q.db.Query(ctx, listAllRequests,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
		arg.Column7,
		arg.Column8,
		arg.Column9,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllRequestsRow{}
	for rows.Next() {
		var i ListAllRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestNumber,
			&i.ClientID,
			&i.ServiceID,
			&i.Description,
			&i.PreferredDate,
			&i.PreferredTime,
			&i.Urgency,
			&i.FullName,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.City,
			&i.Area,
			&i.Status,
			&i.AssignedWorkerID,
			&i.InternalNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VendorID,
			&i.ServiceName,
			&i.ServiceCount,
			&i.ServiceSummary,
			&i.ClientName,
			&i.WorkerNames,
			&i.VendorID_2,
			&i.VendorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestImages = `-- name: ListRequestImages :many
SELECT id, request_id, url, created_at FROM request_images WHERE request_id = $1
`

func (q *Queries) ListRequestImages(ctx context.Context, requestID uuid.UUID) ([]RequestImage, error) {
	rows, err := q.db.Query(ctx, listRequestImages, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequestImage{}
	for rows.Next() {
		var i RequestImage
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Url,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestLineItems = `-- name: ListRequestLineItems :many
SELECT rli.id, rli.request_id, rli.service_id, rli.created_at, s.name AS service_name, s.price AS service_price
FROM request_line_items rli
JOIN services s ON s.id = rli.service_id
WHERE rli.request_id = $1
ORDER BY rli.created_at
`

type ListRequestLineItemsRow struct {
	ID           uuid.UUID `db:"id" json:"id"`
	RequestID    uuid.UUID `db:"request_id" json:"request_id"`
	ServiceID    uuid.UUID `db:"service_id" json:"service_id"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
	ServiceName  string    `db:"service_name" json:"service_name"`
	ServicePrice string    `db:"service_price" json:"service_price"`
}

func (q *Queries) ListRequestLineItems(ctx context.Context, requestID uuid.UUID) ([]ListRequestLineItemsRow, error) {
	rows, err := q.db.Query(ctx, listRequestLineItems, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestLineItemsRow{}
	for rows.Next() {
		var i ListRequestLineItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.ServiceID,
			&i.CreatedAt,
			&i.ServiceName,
			&i.ServicePrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByClient = `-- name: ListRequestsByClient :many
SELECT
    sr.id, sr.request_number, sr.client_id, sr.service_id, sr.description, sr.preferred_date, sr.preferred_time, sr.urgency, sr.full_name, sr.phone, sr.email, sr.address, sr.city, sr.area, sr.status, sr.assigned_worker_id, sr.internal_notes, sr.created_at, sr.updated_at, sr.vendor_id,
    s.name AS service_name,
    COALESCE(li.service_count, 1::bigint) AS service_count,
    COALESCE(li.service_summary, s.name) AS service_summary
FROM service_requests sr
JOIN services s ON s.id = sr.service_id
LEFT JOIN (
    SELECT
        rli.request_id,
        COUNT(*)::bigint AS service_count,
        STRING_AGG(s.name, ', ' ORDER BY rli.created_at) AS service_summary
    FROM request_line_items rli
    JOIN services s ON s.id = rli.service_id
    GROUP BY rli.request_id
) li ON li.request_id = sr.id
WHERE sr.client_id = $1
ORDER BY sr.created_at DESC
LIMIT $2 OFFSET $3
`

type ListRequestsByClientParams struct {
	ClientID uuid.UUID `db:"client_id" json:"client_id"`
	Limit    int32     `db:"limit" json:"limit"`
	Offset   int32     `db:"offset" json:"offset"`
}

type ListRequestsByClientRow struct {
	ID               uuid.UUID   `db:"id" json:"id"`
	RequestNumber    string      `db:"request_number" json:"request_number"`
	ClientID         uuid.UUID   `db:"client_id" json:"client_id"`
	ServiceID        uuid.UUID   `db:"service_id" json:"service_id"`
	Description      string      `db:"description" json:"description"`
	PreferredDate    time.Time   `db:"preferred_date" json:"preferred_date"`
	PreferredTime    string      `db:"preferred_time" json:"preferred_time"`
	Urgency          string      `db:"urgency" json:"urgency"`
	FullName         string      `db:"full_name" json:"full_name"`
	Phone            string      `db:"phone" json:"phone"`
	Email            string      `db:"email" json:"email"`
	Address          string      `db:"address" json:"address"`
	City             string      `db:"city" json:"city"`
	Area             string      `db:"area" json:"area"`
	Status           string      `db:"status" json:"status"`
	AssignedWorkerID pgtype.UUID `db:"assigned_worker_id" json:"assigned_worker_id"`
	InternalNotes    *string     `db:"internal_notes" json:"internal_notes"`
	CreatedAt        time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time   `db:"updated_at" json:"updated_at"`
	VendorID         pgtype.UUID `db:"vendor_id" json:"vendor_id"`
	ServiceName      string      `db:"service_name" json:"service_name"`
	ServiceCount     int64       `db:"service_count" json:"service_count"`
	ServiceSummary   []byte      `db:"service_summary" json:"service_summary"`
}

func (q *Queries) ListRequestsByClient(ctx context.Context, arg ListRequestsByClientParams) ([]ListRequestsByClientRow, error) {
	rows, err := q.db.Query(ctx, listRequestsByClient, arg.ClientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestsByClientRow{}
	for rows.Next() {
		var i ListRequestsByClientRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestNumber,
			&i.ClientID,
			&i.ServiceID,
			&i.Description,
			&i.PreferredDate,
			&i.PreferredTime,
			&i.Urgency,
			&i.FullName,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.City,
			&i.Area,
			&i.Status,
			&i.AssignedWorkerID,
			&i.InternalNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VendorID,
			&i.ServiceName,
			&i.ServiceCount,
			&i.ServiceSummary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRequestInvoiced = `-- name: MarkRequestInvoiced :one
UPDATE service_requests
SET status = 'invoiced', updated_at = NOW()
WHERE id = $1
RETURNING id, request_number, client_id, service_id, description, preferred_date, preferred_time, urgency, full_name, phone, email, address, city, area, status, assigned_worker_id, internal_notes, created_at, updated_at, vendor_id
`

func (q *Queries) MarkRequestInvoiced(ctx context.Context, id uuid.UUID) (ServiceRequest, error) {
	row := q.db.QueryRow(ctx, markRequestInvoiced, id)
	var i ServiceRequest
	err := row.Scan(
		&i.ID,
		&i.RequestNumber,
		&i.ClientID,
		&i.ServiceID,
		&i.Description,
		&i.PreferredDate,
		&i.PreferredTime,
		&i.Urgency,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.City,
		&i.Area,
		&i.Status,
		&i.AssignedWorkerID,
		&i.InternalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VendorID,
	)
	return i, err
}

const setRequestAssignedWorker = `-- name: SetRequestAssignedWorker :one
UPDATE service_requests
SET assigned_worker_id = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, request_number, client_id, service_id, description, preferred_date, preferred_time, urgency, full_name, phone, email, address, city, area, status, assigned_worker_id, internal_notes, created_at, updated_at, vendor_id
`

type SetRequestAssignedWorkerParams struct {
	ID               uuid.UUID   `db:"id" json:"id"`
	AssignedWorkerID pgtype.UUID `db:"assigned_worker_id" json:"assigned_worker_id"`
}

func (q *Queries) SetRequestAssignedWorker(ctx context.Context, arg SetRequestAssignedWorkerParams) (ServiceRequest, error) {
	row := q.db.QueryRow(ctx, setRequestAssignedWorker, arg.ID, arg.AssignedWorkerID)
	var i ServiceRequest
	err := row.Scan(
		&i.ID,
		&i.RequestNumber,
		&i.ClientID,
		&i.ServiceID,
		&i.Description,
		&i.PreferredDate,
		&i.PreferredTime,
		&i.Urgency,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.City,
		&i.Area,
		&i.Status,
		&i.AssignedWorkerID,
		&i.InternalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VendorID,
	)
	return i, err
}

const setRequestVendor = `-- name: SetRequestVendor :one
UPDATE service_requests
SET vendor_id = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, request_number, client_id, service_id, description, preferred_date, preferred_time, urgency, full_name, phone, email, address, city, area, status, assigned_worker_id, internal_notes, created_at, updated_at, vendor_id
`

type SetRequestVendorParams struct {
	ID       uuid.UUID   `db:"id" json:"id"`
	VendorID pgtype.UUID `db:"vendor_id" json:"vendor_id"`
}

func (q *Queries) SetRequestVendor(ctx context.Context, arg SetRequestVendorParams) (ServiceRequest, error) {
	row := q.db.QueryRow(ctx, setRequestVendor, arg.ID, arg.VendorID)
	var i ServiceRequest
	err := row.Scan(
		&i.ID,
		&i.RequestNumber,
		&i.ClientID,
		&i.ServiceID,
		&i.Description,
		&i.PreferredDate,
		&i.PreferredTime,
		&i.Urgency,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.City,
		&i.Area,
		&i.Status,
		&i.AssignedWorkerID,
		&i.InternalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VendorID,
	)
	return i, err
}

const updateRequest = `-- name: UpdateRequest :one
UPDATE service_requests
SET
    status             = COALESCE($2, status),
    assigned_worker_id = COALESCE($3, assigned_worker_id),
    internal_notes     = COALESCE($4, internal_notes),
    updated_at         = NOW()
WHERE id = $1
RETURNING id, request_number, client_id, service_id, description, preferred_date, preferred_time, urgency, full_name, phone, email, address, city, area, status, assigned_worker_id, internal_notes, created_at, updated_at, vendor_id
`

type UpdateRequestParams struct {
	ID               uuid.UUID   `db:"id" json:"id"`
	Status           *string     `db:"status" json:"status"`
	AssignedWorkerID pgtype.UUID `db:"assigned_worker_id" json:"assigned_worker_id"`
	InternalNotes    *string     `db:"internal_notes" json:"internal_notes"`
}

func (q *Queries) UpdateRequest(ctx context.Context, arg UpdateRequestParams) (ServiceRequest, error) {
	row := q.db.QueryRow(ctx, updateRequest,
		arg.ID,
		arg.Status,
		arg.AssignedWorkerID,
		arg.InternalNotes,
	)
	var i ServiceRequest
	err := row.Scan(
		&i.ID,
		&i.RequestNumber,
		&i.ClientID,
		&i.ServiceID,
		&i.Description,
		&i.PreferredDate,
		&i.PreferredTime,
		&i.Urgency,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.City,
		&i.Area,
		&i.Status,
		&i.AssignedWorkerID,
		&i.InternalNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VendorID,
	)
	return i, err
}
