// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: request_workers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignWorkerToRequest = `-- name: AssignWorkerToRequest :exec
INSERT INTO request_workers (request_id, worker_id, assigned_by)
VALUES ($1, $2, $3)
ON CONFLICT (request_id, worker_id) DO NOTHING
`

type AssignWorkerToRequestParams struct {
	RequestID  uuid.UUID   `db:"request_id" json:"request_id"`
	WorkerID   uuid.UUID   `db:"worker_id" json:"worker_id"`
	AssignedBy pgtype.UUID `db:"assigned_by" json:"assigned_by"`
}

func (q *Queries) AssignWorkerToRequest(ctx context.Context, arg AssignWorkerToRequestParams) error {
	_, err := q.db.Exec(ctx, assignWorkerToRequest, arg.RequestID, arg.WorkerID, arg.AssignedBy)
	return err
}

const clearRequestWorkers = `-- name: ClearRequestWorkers :exec
DELETE FROM request_workers WHERE request_id = $1
`

func (q *Queries) ClearRequestWorkers(ctx context.Context, requestID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearRequestWorkers, requestID)
	return err
}

const countRequestWorkers = `-- name: CountRequestWorkers :one
SELECT COUNT(*) FROM request_workers WHERE request_id = $1
`

func (q *Queries) CountRequestWorkers(ctx context.Context, requestID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestWorkers, requestID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listRequestWorkerIDs = `-- name: ListRequestWorkerIDs :many
SELECT worker_id FROM request_workers WHERE request_id = $1
`

func (q *Queries) ListRequestWorkerIDs(ctx context.Context, requestID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listRequestWorkerIDs, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var worker_id uuid.UUID
		if err := rows.Scan(&worker_id); err != nil {
			return nil, err
		}
		items = append(items, worker_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkersByRequest = `-- name: ListWorkersByRequest :many
SELECT w.id, w.name, w.phone, w.cnic, w.trades, w.compensation_type, w.monthly_salary, w.commission_pct, w.min_guarantee, w.availability_days, w.availability_start, w.availability_end, w.status, w.notes, w.created_at, w.updated_at
FROM workers w
JOIN request_workers rw ON rw.worker_id = w.id
WHERE rw.request_id = $1
ORDER BY w.name ASC
`

func (q *Queries) ListWorkersByRequest(ctx context.Context, requestID uuid.UUID) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listWorkersByRequest, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Worker{}
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Cnic,
			&i.Trades,
			&i.CompensationType,
			&i.MonthlySalary,
			&i.CommissionPct,
			&i.MinGuarantee,
			&i.AvailabilityDays,
			&i.AvailabilityStart,
			&i.AvailabilityEnd,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWorkerFromRequest = `-- name: RemoveWorkerFromRequest :exec
DELETE FROM request_workers
WHERE request_id = $1 AND worker_id = $2
`

type RemoveWorkerFromRequestParams struct {
	RequestID uuid.UUID `db:"request_id" json:"request_id"`
	WorkerID  uuid.UUID `db:"worker_id" json:"worker_id"`
}

func (q *Queries) RemoveWorkerFromRequest(ctx context.Context, arg RemoveWorkerFromRequestParams) error {
	_, err := q.db.Exec(ctx, removeWorkerFromRequest, arg.RequestID, arg.WorkerID)
	return err
}
