// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: services.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSubCategories = `-- name: CountSubCategories :one
SELECT COUNT(*) FROM services WHERE parent_id = $1
`

func (q *Queries) CountSubCategories(ctx context.Context, parentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSubCategories, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (name, description, icon, parent_id, is_subcategory)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, icon, created_at, parent_id, is_subcategory
`

type CreateServiceParams struct {
	Name          string      `db:"name" json:"name"`
	Description   string      `db:"description" json:"description"`
	Icon          string      `db:"icon" json:"icon"`
	ParentID      pgtype.UUID `db:"parent_id" json:"parent_id"`
	IsSubcategory bool        `db:"is_subcategory" json:"is_subcategory"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.ParentID,
		arg.IsSubcategory,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.CreatedAt,
		&i.ParentID,
		&i.IsSubcategory,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, name, description, icon, created_at, parent_id, is_subcategory FROM services WHERE id = $1
`

func (q *Queries) GetServiceByID(ctx context.Context, id uuid.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.CreatedAt,
		&i.ParentID,
		&i.IsSubcategory,
	)
	return i, err
}

const listAllServicesWithParent = `-- name: ListAllServicesWithParent :many
SELECT
    s.id, s.name, s.description, s.icon, s.created_at, s.parent_id, s.is_subcategory,
    p.name as parent_name
FROM services s
LEFT JOIN services p ON s.parent_id = p.id
ORDER BY COALESCE(p.name, s.name), s.name
`

type ListAllServicesWithParentRow struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	Name          string      `db:"name" json:"name"`
	Description   string      `db:"description" json:"description"`
	Icon          string      `db:"icon" json:"icon"`
	CreatedAt     time.Time   `db:"created_at" json:"created_at"`
	ParentID      pgtype.UUID `db:"parent_id" json:"parent_id"`
	IsSubcategory bool        `db:"is_subcategory" json:"is_subcategory"`
	ParentName    *string     `db:"parent_name" json:"parent_name"`
}

func (q *Queries) ListAllServicesWithParent(ctx context.Context) ([]ListAllServicesWithParentRow, error) {
	rows, err := q.db.Query(ctx, listAllServicesWithParent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllServicesWithParentRow{}
	for rows.Next() {
		var i ListAllServicesWithParentRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.CreatedAt,
			&i.ParentID,
			&i.IsSubcategory,
			&i.ParentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceCategories = `-- name: ListServiceCategories :many
SELECT id, name, description, icon, created_at, parent_id, is_subcategory FROM services WHERE parent_id IS NULL ORDER BY name ASC
`

func (q *Queries) ListServiceCategories(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServiceCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.CreatedAt,
			&i.ParentID,
			&i.IsSubcategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServices = `-- name: ListServices :many
SELECT id, name, description, icon, created_at, parent_id, is_subcategory FROM services ORDER BY name ASC
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.CreatedAt,
			&i.ParentID,
			&i.IsSubcategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubCategories = `-- name: ListSubCategories :many
SELECT id, name, description, icon, created_at, parent_id, is_subcategory FROM services WHERE parent_id = $1 ORDER BY name ASC
`

func (q *Queries) ListSubCategories(ctx context.Context, parentID pgtype.UUID) ([]Service, error) {
	rows, err := q.db.Query(ctx, listSubCategories, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.CreatedAt,
			&i.ParentID,
			&i.IsSubcategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET
    name           = COALESCE($2, name),
    description    = COALESCE($3, description),
    icon           = COALESCE($4, icon),
    parent_id      = COALESCE($5, parent_id),
    is_subcategory = COALESCE($6, is_subcategory)
WHERE id = $1
RETURNING id, name, description, icon, created_at, parent_id, is_subcategory
`

type UpdateServiceParams struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	Name          *string     `db:"name" json:"name"`
	Description   *string     `db:"description" json:"description"`
	Icon          *string     `db:"icon" json:"icon"`
	ParentID      pgtype.UUID `db:"parent_id" json:"parent_id"`
	IsSubcategory *bool       `db:"is_subcategory" json:"is_subcategory"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.ParentID,
		arg.IsSubcategory,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.CreatedAt,
		&i.ParentID,
		&i.IsSubcategory,
	)
	return i, err
}
