// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, password_hash, role, created_at, updated_at
`

type CreateUserParams struct {
	Name         string `db:"name" json:"name"`
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
	Role         string `db:"role" json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminCount = `-- name: GetAdminCount :one
SELECT COUNT(*) FROM users WHERE role = 'admin'
`

func (q *Queries) GetAdminCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getAdminCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFirstAdmin = `-- name: GetFirstAdmin :one
SELECT id, name, email, password_hash, role, created_at, updated_at FROM users WHERE role = 'admin' LIMIT 1
`

func (q *Queries) GetFirstAdmin(ctx context.Context) (User, error) {
	row := q.db.QueryRow(ctx, getFirstAdmin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, role, created_at, updated_at FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, role, created_at, updated_at FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, name, email FROM users WHERE role = 'client' ORDER BY name
`

type ListClientsRow struct {
	ID    uuid.UUID `db:"id" json:"id"`
	Name  string    `db:"name" json:"name"`
	Email string    `db:"email" json:"email"`
}

func (q *Queries) ListClients(ctx context.Context) ([]ListClientsRow, error) {
	rows, err := q.db.Query(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientsRow{}
	for rows.Next() {
		var i ListClientsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdminByEmail = `-- name: UpdateAdminByEmail :one
UPDATE users
SET
    name          = COALESCE($2, name),
    email         = COALESCE($3, email),
    password_hash = COALESCE($4, password_hash),
    updated_at    = NOW()
WHERE email = $1 AND role = 'admin'
RETURNING id, name, email, password_hash, role, created_at, updated_at
`

type UpdateAdminByEmailParams struct {
	Email        string  `db:"email" json:"email"`
	Name         *string `db:"name" json:"name"`
	NewEmail     *string `db:"new_email" json:"new_email"`
	PasswordHash *string `db:"password_hash" json:"password_hash"`
}

func (q *Queries) UpdateAdminByEmail(ctx context.Context, arg UpdateAdminByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, updateAdminByEmail,
		arg.Email,
		arg.Name,
		arg.NewEmail,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAdminByID = `-- name: UpdateAdminByID :one
UPDATE users
SET
    name          = COALESCE($2, name),
    email         = COALESCE($3, email),
    password_hash = COALESCE($4, password_hash),
    updated_at    = NOW()
WHERE id = $1 AND role = 'admin'
RETURNING id, name, email, password_hash, role, created_at, updated_at
`

type UpdateAdminByIDParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	Name         *string   `db:"name" json:"name"`
	Email        *string   `db:"email" json:"email"`
	PasswordHash *string   `db:"password_hash" json:"password_hash"`
}

func (q *Queries) UpdateAdminByID(ctx context.Context, arg UpdateAdminByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, updateAdminByID,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
