// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: vendors.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignVendorToRequest = `-- name: AssignVendorToRequest :one
INSERT INTO request_vendors (
    request_id, vendor_id
) VALUES ($1, $2)
RETURNING id, request_id, vendor_id, created_at, updated_at
`

type AssignVendorToRequestParams struct {
	RequestID uuid.UUID `db:"request_id" json:"request_id"`
	VendorID  uuid.UUID `db:"vendor_id" json:"vendor_id"`
}

func (q *Queries) AssignVendorToRequest(ctx context.Context, arg AssignVendorToRequestParams) (RequestVendor, error) {
	row := q.db.QueryRow(ctx, assignVendorToRequest, arg.RequestID, arg.VendorID)
	var i RequestVendor
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.VendorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countVendorAssignedRequests = `-- name: CountVendorAssignedRequests :one
SELECT COUNT(*) FROM service_requests WHERE vendor_id = $1
`

func (q *Queries) CountVendorAssignedRequests(ctx context.Context, vendorID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVendorAssignedRequests, vendorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVendors = `-- name: CountVendors :one
SELECT COUNT(*) FROM vendors
WHERE
    ($1::text IS NULL OR $1 = '' OR name ILIKE '%' || $1 || '%') AND
    ($2::text IS NULL OR $2 = '' OR status = $2)
`

type CountVendorsParams struct {
	Search *string `db:"search" json:"search"`
	Status *string `db:"status" json:"status"`
}

func (q *Queries) CountVendors(ctx context.Context, arg CountVendorsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVendors, arg.Search, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVendor = `-- name: CreateVendor :one
INSERT INTO vendors (
    name, contact_name, contact_phone, contact_email,
    services_offered, notes
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, contact_name, contact_phone, contact_email, services_offered, status, notes, created_at, updated_at
`

type CreateVendorParams struct {
	Name            string   `db:"name" json:"name"`
	ContactName     *string  `db:"contact_name" json:"contact_name"`
	ContactPhone    string   `db:"contact_phone" json:"contact_phone"`
	ContactEmail    *string  `db:"contact_email" json:"contact_email"`
	ServicesOffered []string `db:"services_offered" json:"services_offered"`
	Notes           *string  `db:"notes" json:"notes"`
}

func (q *Queries) CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, createVendor,
		arg.Name,
		arg.ContactName,
		arg.ContactPhone,
		arg.ContactEmail,
		arg.ServicesOffered,
		arg.Notes,
	)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactName,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.ServicesOffered,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVendor = `-- name: DeleteVendor :one
UPDATE vendors
SET status = 'inactive', updated_at = NOW()
WHERE id = $1
RETURNING id, name, contact_name, contact_phone, contact_email, services_offered, status, notes, created_at, updated_at
`

func (q *Queries) DeleteVendor(ctx context.Context, id uuid.UUID) (Vendor, error) {
	row := q.db.QueryRow(ctx, deleteVendor, id)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactName,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.ServicesOffered,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveVendors = `-- name: GetActiveVendors :many
SELECT id, name, contact_name, contact_phone, contact_email, services_offered, status, notes, created_at, updated_at FROM vendors
WHERE status = 'active'
ORDER BY name ASC
`

func (q *Queries) GetActiveVendors(ctx context.Context) ([]Vendor, error) {
	rows, err := q.db.Query(ctx, getActiveVendors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vendor{}
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContactName,
			&i.ContactPhone,
			&i.ContactEmail,
			&i.ServicesOffered,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRequestVendorDetails = `-- name: GetRequestVendorDetails :one
SELECT
    rv.id,
    rv.request_id,
    rv.vendor_id,
    rv.created_at,
    rv.updated_at,
    v.name AS vendor_name,
    v.contact_name AS vendor_contact_name,
    v.contact_phone AS vendor_contact_phone,
    v.contact_email AS vendor_contact_email,
    v.services_offered AS vendor_services_offered,
    v.status AS vendor_status
FROM request_vendors rv
JOIN vendors v ON v.id = rv.vendor_id
WHERE rv.request_id = $1
`

type GetRequestVendorDetailsRow struct {
	ID                    uuid.UUID `db:"id" json:"id"`
	RequestID             uuid.UUID `db:"request_id" json:"request_id"`
	VendorID              uuid.UUID `db:"vendor_id" json:"vendor_id"`
	CreatedAt             time.Time `db:"created_at" json:"created_at"`
	UpdatedAt             time.Time `db:"updated_at" json:"updated_at"`
	VendorName            string    `db:"vendor_name" json:"vendor_name"`
	VendorContactName     *string   `db:"vendor_contact_name" json:"vendor_contact_name"`
	VendorContactPhone    string    `db:"vendor_contact_phone" json:"vendor_contact_phone"`
	VendorContactEmail    *string   `db:"vendor_contact_email" json:"vendor_contact_email"`
	VendorServicesOffered []string  `db:"vendor_services_offered" json:"vendor_services_offered"`
	VendorStatus          string    `db:"vendor_status" json:"vendor_status"`
}

func (q *Queries) GetRequestVendorDetails(ctx context.Context, requestID uuid.UUID) (GetRequestVendorDetailsRow, error) {
	row := q.db.QueryRow(ctx, getRequestVendorDetails, requestID)
	var i GetRequestVendorDetailsRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.VendorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VendorName,
		&i.VendorContactName,
		&i.VendorContactPhone,
		&i.VendorContactEmail,
		&i.VendorServicesOffered,
		&i.VendorStatus,
	)
	return i, err
}

const getVendorByID = `-- name: GetVendorByID :one
SELECT id, name, contact_name, contact_phone, contact_email, services_offered, status, notes, created_at, updated_at FROM vendors WHERE id = $1
`

func (q *Queries) GetVendorByID(ctx context.Context, id uuid.UUID) (Vendor, error) {
	row := q.db.QueryRow(ctx, getVendorByID, id)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactName,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.ServicesOffered,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVendorInvoices = `-- name: GetVendorInvoices :many
SELECT
    i.id,
    i.invoice_number,
    i.total,
    i.vendor_commission,
    i.status,
    i.created_at,
    r.request_number,
    s.name AS service_name
FROM invoices i
JOIN service_requests r ON r.id = i.request_id
JOIN services s ON s.id = r.service_id
WHERE r.vendor_id = $1
ORDER BY i.created_at DESC
`

type GetVendorInvoicesRow struct {
	ID               uuid.UUID      `db:"id" json:"id"`
	InvoiceNumber    string         `db:"invoice_number" json:"invoice_number"`
	Total            pgtype.Numeric `db:"total" json:"total"`
	VendorCommission pgtype.Numeric `db:"vendor_commission" json:"vendor_commission"`
	Status           string         `db:"status" json:"status"`
	CreatedAt        time.Time      `db:"created_at" json:"created_at"`
	RequestNumber    string         `db:"request_number" json:"request_number"`
	ServiceName      string         `db:"service_name" json:"service_name"`
}

func (q *Queries) GetVendorInvoices(ctx context.Context, vendorID pgtype.UUID) ([]GetVendorInvoicesRow, error) {
	rows, err := q.db.Query(ctx, getVendorInvoices, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVendorInvoicesRow{}
	for rows.Next() {
		var i GetVendorInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.Total,
			&i.VendorCommission,
			&i.Status,
			&i.CreatedAt,
			&i.RequestNumber,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVendorProfile = `-- name: GetVendorProfile :one
SELECT
    v.id,
    v.name,
    v.status,
    v.services_offered,
    v.contact_name,
    v.contact_phone,
    v.contact_email,
    v.notes,
    COALESCE(SUM(
        CASE WHEN i.status = 'paid' THEN i.vendor_commission ELSE 0 END
    ), 0)::numeric AS total_commissions,
    COUNT(CASE WHEN i.status = 'paid' THEN 1 END)::integer AS commission_count,
    COUNT(r.id)::integer AS jobs_count
FROM vendors v
LEFT JOIN service_requests r ON r.vendor_id = v.id
LEFT JOIN invoices i ON i.request_id = r.id
WHERE v.id = $1
GROUP BY v.id
`

type GetVendorProfileRow struct {
	ID               uuid.UUID      `db:"id" json:"id"`
	Name             string         `db:"name" json:"name"`
	Status           string         `db:"status" json:"status"`
	ServicesOffered  []string       `db:"services_offered" json:"services_offered"`
	ContactName      *string        `db:"contact_name" json:"contact_name"`
	ContactPhone     string         `db:"contact_phone" json:"contact_phone"`
	ContactEmail     *string        `db:"contact_email" json:"contact_email"`
	Notes            *string        `db:"notes" json:"notes"`
	TotalCommissions pgtype.Numeric `db:"total_commissions" json:"total_commissions"`
	CommissionCount  int32          `db:"commission_count" json:"commission_count"`
	JobsCount        int32          `db:"jobs_count" json:"jobs_count"`
}

func (q *Queries) GetVendorProfile(ctx context.Context, id uuid.UUID) (GetVendorProfileRow, error) {
	row := q.db.QueryRow(ctx, getVendorProfile, id)
	var i GetVendorProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.ServicesOffered,
		&i.ContactName,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.Notes,
		&i.TotalCommissions,
		&i.CommissionCount,
		&i.JobsCount,
	)
	return i, err
}

const getVendorRequests = `-- name: GetVendorRequests :many
SELECT
    r.id,
    r.request_number,
    r.full_name,
    r.status,
    r.preferred_date,
    s.name AS service_name
FROM service_requests r
JOIN services s ON s.id = r.service_id
WHERE r.vendor_id = $1
ORDER BY r.preferred_date DESC
`

type GetVendorRequestsRow struct {
	ID            uuid.UUID `db:"id" json:"id"`
	RequestNumber string    `db:"request_number" json:"request_number"`
	FullName      string    `db:"full_name" json:"full_name"`
	Status        string    `db:"status" json:"status"`
	PreferredDate time.Time `db:"preferred_date" json:"preferred_date"`
	ServiceName   string    `db:"service_name" json:"service_name"`
}

func (q *Queries) GetVendorRequests(ctx context.Context, vendorID pgtype.UUID) ([]GetVendorRequestsRow, error) {
	rows, err := q.db.Query(ctx, getVendorRequests, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVendorRequestsRow{}
	for rows.Next() {
		var i GetVendorRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestNumber,
			&i.FullName,
			&i.Status,
			&i.PreferredDate,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendors = `-- name: ListVendors :many
SELECT id, name, contact_name, contact_phone, contact_email, services_offered, status, notes, created_at, updated_at FROM vendors
WHERE
    ($1::text IS NULL OR $1 = '' OR name ILIKE '%' || $1 || '%') AND
    ($2::text IS NULL OR $2 = '' OR status = $2)
ORDER BY name ASC
LIMIT $4 OFFSET $3
`

type ListVendorsParams struct {
	Search *string `db:"search" json:"search"`
	Status *string `db:"status" json:"status"`
	Offset int32   `db:"offset" json:"offset"`
	Limit  int32   `db:"limit" json:"limit"`
}

func (q *Queries) ListVendors(ctx context.Context, arg ListVendorsParams) ([]Vendor, error) {
	rows, err := q.db.Query(ctx, listVendors,
		arg.Search,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vendor{}
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContactName,
			&i.ContactPhone,
			&i.ContactEmail,
			&i.ServicesOffered,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeVendorFromRequest = `-- name: RemoveVendorFromRequest :exec
DELETE FROM request_vendors
WHERE request_id = $1
`

func (q *Queries) RemoveVendorFromRequest(ctx context.Context, requestID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeVendorFromRequest, requestID)
	return err
}

const updateVendor = `-- name: UpdateVendor :one
UPDATE vendors
SET
    name             = COALESCE($2, name),
    contact_name     = COALESCE($3, contact_name),
    contact_phone    = COALESCE($4, contact_phone),
    contact_email    = COALESCE($5, contact_email),
    services_offered = COALESCE($6, services_offered),
    notes            = COALESCE($7, notes),
    status           = COALESCE($8, status),
    updated_at       = NOW()
WHERE id = $1
RETURNING id, name, contact_name, contact_phone, contact_email, services_offered, status, notes, created_at, updated_at
`

type UpdateVendorParams struct {
	ID              uuid.UUID `db:"id" json:"id"`
	Name            *string   `db:"name" json:"name"`
	ContactName     *string   `db:"contact_name" json:"contact_name"`
	ContactPhone    *string   `db:"contact_phone" json:"contact_phone"`
	ContactEmail    *string   `db:"contact_email" json:"contact_email"`
	ServicesOffered []string  `db:"services_offered" json:"services_offered"`
	Notes           *string   `db:"notes" json:"notes"`
	Status          *string   `db:"status" json:"status"`
}

func (q *Queries) UpdateVendor(ctx context.Context, arg UpdateVendorParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, updateVendor,
		arg.ID,
		arg.Name,
		arg.ContactName,
		arg.ContactPhone,
		arg.ContactEmail,
		arg.ServicesOffered,
		arg.Notes,
		arg.Status,
	)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactName,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.ServicesOffered,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
