// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: workers.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveWorkers = `-- name: CountActiveWorkers :one
SELECT COUNT(*) FROM workers WHERE status = 'active'
`

func (q *Queries) CountActiveWorkers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveWorkers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkerRequests = `-- name: CountWorkerRequests :one
SELECT COUNT(*) FROM request_workers WHERE worker_id = $1
`

func (q *Queries) CountWorkerRequests(ctx context.Context, workerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkerRequests, workerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkersOnLeave = `-- name: CountWorkersOnLeave :one
SELECT COUNT(*) FROM workers WHERE status = 'on_leave'
`

func (q *Queries) CountWorkersOnLeave(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkersOnLeave)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorker = `-- name: CreateWorker :one
INSERT INTO workers (
    name, phone, cnic, trades, compensation_type,
    monthly_salary, commission_pct, min_guarantee,
    availability_days, availability_start, availability_end,
    status, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, name, phone, cnic, trades, compensation_type, monthly_salary, commission_pct, min_guarantee, availability_days, availability_start, availability_end, status, notes, created_at, updated_at
`

type CreateWorkerParams struct {
	Name              string         `db:"name" json:"name"`
	Phone             string         `db:"phone" json:"phone"`
	Cnic              *string        `db:"cnic" json:"cnic"`
	Trades            []string       `db:"trades" json:"trades"`
	CompensationType  string         `db:"compensation_type" json:"compensation_type"`
	MonthlySalary     pgtype.Numeric `db:"monthly_salary" json:"monthly_salary"`
	CommissionPct     pgtype.Numeric `db:"commission_pct" json:"commission_pct"`
	MinGuarantee      pgtype.Numeric `db:"min_guarantee" json:"min_guarantee"`
	AvailabilityDays  []int32        `db:"availability_days" json:"availability_days"`
	AvailabilityStart pgtype.Time    `db:"availability_start" json:"availability_start"`
	AvailabilityEnd   pgtype.Time    `db:"availability_end" json:"availability_end"`
	Status            string         `db:"status" json:"status"`
	Notes             *string        `db:"notes" json:"notes"`
}

func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, createWorker,
		arg.Name,
		arg.Phone,
		arg.Cnic,
		arg.Trades,
		arg.CompensationType,
		arg.MonthlySalary,
		arg.CommissionPct,
		arg.MinGuarantee,
		arg.AvailabilityDays,
		arg.AvailabilityStart,
		arg.AvailabilityEnd,
		arg.Status,
		arg.Notes,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Cnic,
		&i.Trades,
		&i.CompensationType,
		&i.MonthlySalary,
		&i.CommissionPct,
		&i.MinGuarantee,
		&i.AvailabilityDays,
		&i.AvailabilityStart,
		&i.AvailabilityEnd,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorker = `-- name: DeleteWorker :exec
DELETE FROM workers WHERE id = $1
`

func (q *Queries) DeleteWorker(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorker, id)
	return err
}

const getWorkerByID = `-- name: GetWorkerByID :one
SELECT id, name, phone, cnic, trades, compensation_type, monthly_salary, commission_pct, min_guarantee, availability_days, availability_start, availability_end, status, notes, created_at, updated_at FROM workers WHERE id = $1
`

func (q *Queries) GetWorkerByID(ctx context.Context, id uuid.UUID) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorkerByID, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Cnic,
		&i.Trades,
		&i.CompensationType,
		&i.MonthlySalary,
		&i.CommissionPct,
		&i.MinGuarantee,
		&i.AvailabilityDays,
		&i.AvailabilityStart,
		&i.AvailabilityEnd,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkerProfile = `-- name: GetWorkerProfile :one
SELECT 
    w.id, w.name, w.phone, w.cnic, w.trades, w.compensation_type, w.monthly_salary, w.commission_pct, w.min_guarantee, w.availability_days, w.availability_start, w.availability_end, w.status, w.notes, w.created_at, w.updated_at,
    COALESCE(SUM(wc.amount), 0)::text as total_commissions,
    COUNT(DISTINCT wc.id)::bigint as commission_count,
    COALESCE(SUM(sp.net_payable), 0)::text as total_salary_paid,
    COUNT(DISTINCT sp.id)::bigint as salary_count,
    COUNT(DISTINCT CASE WHEN sr.status = 'completed' THEN sr.id END)::bigint as jobs_completed
FROM workers w
LEFT JOIN worker_commissions wc ON wc.worker_id = w.id
LEFT JOIN salary_payments sp ON sp.worker_id = w.id AND sp.status = 'paid'
LEFT JOIN request_workers rw ON rw.worker_id = w.id
LEFT JOIN service_requests sr ON sr.id = rw.request_id
WHERE w.id = $1
GROUP BY w.id
`

type GetWorkerProfileRow struct {
	ID                uuid.UUID      `db:"id" json:"id"`
	Name              string         `db:"name" json:"name"`
	Phone             string         `db:"phone" json:"phone"`
	Cnic              *string        `db:"cnic" json:"cnic"`
	Trades            []string       `db:"trades" json:"trades"`
	CompensationType  string         `db:"compensation_type" json:"compensation_type"`
	MonthlySalary     pgtype.Numeric `db:"monthly_salary" json:"monthly_salary"`
	CommissionPct     pgtype.Numeric `db:"commission_pct" json:"commission_pct"`
	MinGuarantee      pgtype.Numeric `db:"min_guarantee" json:"min_guarantee"`
	AvailabilityDays  []int32        `db:"availability_days" json:"availability_days"`
	AvailabilityStart pgtype.Time    `db:"availability_start" json:"availability_start"`
	AvailabilityEnd   pgtype.Time    `db:"availability_end" json:"availability_end"`
	Status            string         `db:"status" json:"status"`
	Notes             *string        `db:"notes" json:"notes"`
	CreatedAt         time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time      `db:"updated_at" json:"updated_at"`
	TotalCommissions  string         `db:"total_commissions" json:"total_commissions"`
	CommissionCount   int64          `db:"commission_count" json:"commission_count"`
	TotalSalaryPaid   string         `db:"total_salary_paid" json:"total_salary_paid"`
	SalaryCount       int64          `db:"salary_count" json:"salary_count"`
	JobsCompleted     int64          `db:"jobs_completed" json:"jobs_completed"`
}

// Worker Profile Queries
func (q *Queries) GetWorkerProfile(ctx context.Context, id uuid.UUID) (GetWorkerProfileRow, error) {
	row := q.db.QueryRow(ctx, getWorkerProfile, id)
	var i GetWorkerProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Cnic,
		&i.Trades,
		&i.CompensationType,
		&i.MonthlySalary,
		&i.CommissionPct,
		&i.MinGuarantee,
		&i.AvailabilityDays,
		&i.AvailabilityStart,
		&i.AvailabilityEnd,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalCommissions,
		&i.CommissionCount,
		&i.TotalSalaryPaid,
		&i.SalaryCount,
		&i.JobsCompleted,
	)
	return i, err
}

const listActiveWorkers = `-- name: ListActiveWorkers :many
SELECT id, name, phone, cnic, trades, compensation_type, monthly_salary, commission_pct, min_guarantee, availability_days, availability_start, availability_end, status, notes, created_at, updated_at FROM workers WHERE status = 'active' ORDER BY name ASC
`

func (q *Queries) ListActiveWorkers(ctx context.Context) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listActiveWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Worker{}
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Cnic,
			&i.Trades,
			&i.CompensationType,
			&i.MonthlySalary,
			&i.CommissionPct,
			&i.MinGuarantee,
			&i.AvailabilityDays,
			&i.AvailabilityStart,
			&i.AvailabilityEnd,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkerRequests = `-- name: ListWorkerRequests :many
SELECT sr.id, sr.request_number, sr.client_id, sr.service_id, sr.description, sr.preferred_date, sr.preferred_time, sr.urgency, sr.full_name, sr.phone, sr.email, sr.address, sr.city, sr.area, sr.status, sr.assigned_worker_id, sr.internal_notes, sr.created_at, sr.updated_at, sr.vendor_id, s.name as service_name
FROM service_requests sr
JOIN request_workers rw ON rw.request_id = sr.id
JOIN services s ON s.id = sr.service_id
WHERE rw.worker_id = $1
ORDER BY sr.created_at DESC
LIMIT $2 OFFSET $3
`

type ListWorkerRequestsParams struct {
	WorkerID uuid.UUID `db:"worker_id" json:"worker_id"`
	Limit    int32     `db:"limit" json:"limit"`
	Offset   int32     `db:"offset" json:"offset"`
}

type ListWorkerRequestsRow struct {
	ID               uuid.UUID   `db:"id" json:"id"`
	RequestNumber    string      `db:"request_number" json:"request_number"`
	ClientID         uuid.UUID   `db:"client_id" json:"client_id"`
	ServiceID        uuid.UUID   `db:"service_id" json:"service_id"`
	Description      string      `db:"description" json:"description"`
	PreferredDate    time.Time   `db:"preferred_date" json:"preferred_date"`
	PreferredTime    string      `db:"preferred_time" json:"preferred_time"`
	Urgency          string      `db:"urgency" json:"urgency"`
	FullName         string      `db:"full_name" json:"full_name"`
	Phone            string      `db:"phone" json:"phone"`
	Email            string      `db:"email" json:"email"`
	Address          string      `db:"address" json:"address"`
	City             string      `db:"city" json:"city"`
	Area             string      `db:"area" json:"area"`
	Status           string      `db:"status" json:"status"`
	AssignedWorkerID pgtype.UUID `db:"assigned_worker_id" json:"assigned_worker_id"`
	InternalNotes    *string     `db:"internal_notes" json:"internal_notes"`
	CreatedAt        time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time   `db:"updated_at" json:"updated_at"`
	VendorID         pgtype.UUID `db:"vendor_id" json:"vendor_id"`
	ServiceName      string      `db:"service_name" json:"service_name"`
}

func (q *Queries) ListWorkerRequests(ctx context.Context, arg ListWorkerRequestsParams) ([]ListWorkerRequestsRow, error) {
	rows, err := q.db.Query(ctx, listWorkerRequests, arg.WorkerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkerRequestsRow{}
	for rows.Next() {
		var i ListWorkerRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestNumber,
			&i.ClientID,
			&i.ServiceID,
			&i.Description,
			&i.PreferredDate,
			&i.PreferredTime,
			&i.Urgency,
			&i.FullName,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.City,
			&i.Area,
			&i.Status,
			&i.AssignedWorkerID,
			&i.InternalNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VendorID,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkers = `-- name: ListWorkers :many
SELECT id, name, phone, cnic, trades, compensation_type, monthly_salary, commission_pct, min_guarantee, availability_days, availability_start, availability_end, status, notes, created_at, updated_at FROM workers ORDER BY name ASC
`

func (q *Queries) ListWorkers(ctx context.Context) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Worker{}
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Cnic,
			&i.Trades,
			&i.CompensationType,
			&i.MonthlySalary,
			&i.CommissionPct,
			&i.MinGuarantee,
			&i.AvailabilityDays,
			&i.AvailabilityStart,
			&i.AvailabilityEnd,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorker = `-- name: UpdateWorker :one
UPDATE workers
SET
    name               = COALESCE($2, name),
    phone              = COALESCE($3, phone),
    cnic               = COALESCE($4, cnic),
    trades             = COALESCE($5, trades),
    compensation_type  = COALESCE($6, compensation_type),
    monthly_salary     = COALESCE($7, monthly_salary),
    commission_pct     = COALESCE($8, commission_pct),
    min_guarantee      = COALESCE($9, min_guarantee),
    availability_days  = COALESCE($10, availability_days),
    availability_start = COALESCE($11, availability_start),
    availability_end   = COALESCE($12, availability_end),
    status             = COALESCE($13, status),
    notes              = COALESCE($14, notes),
    updated_at         = NOW()
WHERE id = $1
RETURNING id, name, phone, cnic, trades, compensation_type, monthly_salary, commission_pct, min_guarantee, availability_days, availability_start, availability_end, status, notes, created_at, updated_at
`

type UpdateWorkerParams struct {
	ID                uuid.UUID      `db:"id" json:"id"`
	Name              *string        `db:"name" json:"name"`
	Phone             *string        `db:"phone" json:"phone"`
	Cnic              *string        `db:"cnic" json:"cnic"`
	Trades            []string       `db:"trades" json:"trades"`
	CompensationType  *string        `db:"compensation_type" json:"compensation_type"`
	MonthlySalary     pgtype.Numeric `db:"monthly_salary" json:"monthly_salary"`
	CommissionPct     pgtype.Numeric `db:"commission_pct" json:"commission_pct"`
	MinGuarantee      pgtype.Numeric `db:"min_guarantee" json:"min_guarantee"`
	AvailabilityDays  []int32        `db:"availability_days" json:"availability_days"`
	AvailabilityStart pgtype.Time    `db:"availability_start" json:"availability_start"`
	AvailabilityEnd   pgtype.Time    `db:"availability_end" json:"availability_end"`
	Status            *string        `db:"status" json:"status"`
	Notes             *string        `db:"notes" json:"notes"`
}

func (q *Queries) UpdateWorker(ctx context.Context, arg UpdateWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, updateWorker,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Cnic,
		arg.Trades,
		arg.CompensationType,
		arg.MonthlySalary,
		arg.CommissionPct,
		arg.MinGuarantee,
		arg.AvailabilityDays,
		arg.AvailabilityStart,
		arg.AvailabilityEnd,
		arg.Status,
		arg.Notes,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Cnic,
		&i.Trades,
		&i.CompensationType,
		&i.MonthlySalary,
		&i.CommissionPct,
		&i.MinGuarantee,
		&i.AvailabilityDays,
		&i.AvailabilityStart,
		&i.AvailabilityEnd,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
